// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: models/animals/v1/animals.proto

package v1

import (
	_ "github.com/ductone/protoc-gen-pgdb/pgdb/v1"
	_ "github.com/pquerna/protoc-gen-dynamo/dynamo/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FurType int32

const (
	FurType_FUR_TYPE_UNSPECIFIED FurType = 0
	FurType_FUR_TYPE_NONE        FurType = 1
	FurType_FUR_TYPE_LOTS        FurType = 2
)

// Enum value maps for FurType.
var (
	FurType_name = map[int32]string{
		0: "FUR_TYPE_UNSPECIFIED",
		1: "FUR_TYPE_NONE",
		2: "FUR_TYPE_LOTS",
	}
	FurType_value = map[string]int32{
		"FUR_TYPE_UNSPECIFIED": 0,
		"FUR_TYPE_NONE":        1,
		"FUR_TYPE_LOTS":        2,
	}
)

func (x FurType) Enum() *FurType {
	p := new(FurType)
	*p = x
	return p
}

func (x FurType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FurType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_animals_v1_animals_proto_enumTypes[0].Descriptor()
}

func (FurType) Type() protoreflect.EnumType {
	return &file_models_animals_v1_animals_proto_enumTypes[0]
}

func (x FurType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FurType.Descriptor instead.
func (FurType) EnumDescriptor() ([]byte, []int) {
	return file_models_animals_v1_animals_proto_rawDescGZIP(), []int{0}
}

type Pet struct {
	state                                                                   protoimpl.MessageState `protogen:"open.v1"`
	TenantId                                                                string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id                                                                      string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt                                                               *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                                                               *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt                                                               *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	DisplayName                                                             string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description                                                             string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	SystemBuiltin                                                           bool                   `protobuf:"varint,9,opt,name=system_builtin,json=systemBuiltin,proto3" json:"system_builtin,omitempty"`
	Elapsed                                                                 *durationpb.Duration   `protobuf:"bytes,10,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Profile                                                                 *structpb.Struct       `protobuf:"bytes,11,opt,name=profile,proto3" json:"profile,omitempty"`
	Cuteness                                                                float32                `protobuf:"fixed32,12,opt,name=cuteness,proto3" json:"cuteness,omitempty"`
	Price                                                                   float64                `protobuf:"fixed64,13,opt,name=price,proto3" json:"price,omitempty"`
	VeryLongNaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaame bool                   `protobuf:"varint,14,opt,name=very_long_naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaame,json=veryLongNaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaame,proto3" json:"very_long_naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaame,omitempty"`
	ExtraProfiles                                                           []*structpb.Struct     `protobuf:"bytes,15,rep,name=extra_profiles,json=extraProfiles,proto3" json:"extra_profiles,omitempty"`
	unknownFields                                                           protoimpl.UnknownFields
	sizeCache                                                               protoimpl.SizeCache
}

func (x *Pet) Reset() {
	*x = Pet{}
	mi := &file_models_animals_v1_animals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_models_animals_v1_animals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_models_animals_v1_animals_proto_rawDescGZIP(), []int{0}
}

func (x *Pet) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Pet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Pet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Pet) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Pet) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Pet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Pet) GetSystemBuiltin() bool {
	if x != nil {
		return x.SystemBuiltin
	}
	return false
}

func (x *Pet) GetElapsed() *durationpb.Duration {
	if x != nil {
		return x.Elapsed
	}
	return nil
}

func (x *Pet) GetProfile() *structpb.Struct {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *Pet) GetCuteness() float32 {
	if x != nil {
		return x.Cuteness
	}
	return 0
}

func (x *Pet) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Pet) GetVeryLongNaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaame() bool {
	if x != nil {
		return x.VeryLongNaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaame
	}
	return false
}

func (x *Pet) GetExtraProfiles() []*structpb.Struct {
	if x != nil {
		return x.ExtraProfiles
	}
	return nil
}

type ScalarValue struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	TenantId         string                  `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id               string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Double           float64                 `protobuf:"fixed64,3,opt,name=double,proto3" json:"double,omitempty"`
	Float            float32                 `protobuf:"fixed32,4,opt,name=float,proto3" json:"float,omitempty"`
	Int32            int32                   `protobuf:"varint,5,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64            int64                   `protobuf:"varint,6,opt,name=int64,proto3" json:"int64,omitempty"`
	Uint32           uint32                  `protobuf:"varint,7,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64           uint64                  `protobuf:"varint,8,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Sint32           int32                   `protobuf:"zigzag32,9,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64           int64                   `protobuf:"zigzag64,10,opt,name=sint64,proto3" json:"sint64,omitempty"`
	Fixed32          uint32                  `protobuf:"fixed32,11,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64          uint64                  `protobuf:"fixed64,12,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32         int32                   `protobuf:"fixed32,13,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64         int64                   `protobuf:"fixed64,14,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Bool             bool                    `protobuf:"varint,15,opt,name=bool,proto3" json:"bool,omitempty"`
	String_          string                  `protobuf:"bytes,16,opt,name=string,proto3" json:"string,omitempty"`
	Bytes            []byte                  `protobuf:"bytes,17,opt,name=bytes,proto3" json:"bytes,omitempty"`
	RepeatedDouble   []float64               `protobuf:"fixed64,23,rep,packed,name=repeated_double,json=repeatedDouble,proto3" json:"repeated_double,omitempty"`
	RepeatedFloat    []float32               `protobuf:"fixed32,24,rep,packed,name=repeated_float,json=repeatedFloat,proto3" json:"repeated_float,omitempty"`
	RepeatedInt32    []int32                 `protobuf:"varint,25,rep,packed,name=repeated_int32,json=repeatedInt32,proto3" json:"repeated_int32,omitempty"`
	RepeatedInt64    []int64                 `protobuf:"varint,26,rep,packed,name=repeated_int64,json=repeatedInt64,proto3" json:"repeated_int64,omitempty"`
	RepeatedUint32   []uint32                `protobuf:"varint,27,rep,packed,name=repeated_uint32,json=repeatedUint32,proto3" json:"repeated_uint32,omitempty"`
	RepeatedUint64   []uint64                `protobuf:"varint,28,rep,packed,name=repeated_uint64,json=repeatedUint64,proto3" json:"repeated_uint64,omitempty"`
	RepeatedSint32   []int32                 `protobuf:"zigzag32,29,rep,packed,name=repeated_sint32,json=repeatedSint32,proto3" json:"repeated_sint32,omitempty"`
	RepeatedSint64   []int64                 `protobuf:"zigzag64,30,rep,packed,name=repeated_sint64,json=repeatedSint64,proto3" json:"repeated_sint64,omitempty"`
	RepeatedFixed32  []uint32                `protobuf:"fixed32,31,rep,packed,name=repeated_fixed32,json=repeatedFixed32,proto3" json:"repeated_fixed32,omitempty"`
	RepeatedFixed64  []uint64                `protobuf:"fixed64,32,rep,packed,name=repeated_fixed64,json=repeatedFixed64,proto3" json:"repeated_fixed64,omitempty"`
	RepeatedSfixed32 []int32                 `protobuf:"fixed32,33,rep,packed,name=repeated_sfixed32,json=repeatedSfixed32,proto3" json:"repeated_sfixed32,omitempty"`
	RepeatedSfixed64 []int64                 `protobuf:"fixed64,34,rep,packed,name=repeated_sfixed64,json=repeatedSfixed64,proto3" json:"repeated_sfixed64,omitempty"`
	RepeatedBool     []bool                  `protobuf:"varint,35,rep,packed,name=repeated_bool,json=repeatedBool,proto3" json:"repeated_bool,omitempty"`
	RepeatedString   []string                `protobuf:"bytes,36,rep,name=repeated_string,json=repeatedString,proto3" json:"repeated_string,omitempty"`
	RepeatedBytes    [][]byte                `protobuf:"bytes,37,rep,name=repeated_bytes,json=repeatedBytes,proto3" json:"repeated_bytes,omitempty"`
	RepeatedEnum     []FurType               `protobuf:"varint,38,rep,packed,name=repeated_enum,json=repeatedEnum,proto3,enum=models.animals.v1.FurType" json:"repeated_enum,omitempty"`
	StringMap        map[string]string       `protobuf:"bytes,39,rep,name=string_map,json=stringMap,proto3" json:"string_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt        *timestamppb.Timestamp  `protobuf:"bytes,40,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StrPtr           *wrapperspb.StringValue `protobuf:"bytes,100,opt,name=str_ptr,json=strPtr,proto3" json:"str_ptr,omitempty"`
	BoolPtr          *wrapperspb.BoolValue   `protobuf:"bytes,101,opt,name=bool_ptr,json=boolPtr,proto3" json:"bool_ptr,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScalarValue) Reset() {
	*x = ScalarValue{}
	mi := &file_models_animals_v1_animals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarValue) ProtoMessage() {}

func (x *ScalarValue) ProtoReflect() protoreflect.Message {
	mi := &file_models_animals_v1_animals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarValue.ProtoReflect.Descriptor instead.
func (*ScalarValue) Descriptor() ([]byte, []int) {
	return file_models_animals_v1_animals_proto_rawDescGZIP(), []int{1}
}

func (x *ScalarValue) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ScalarValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScalarValue) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *ScalarValue) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *ScalarValue) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *ScalarValue) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *ScalarValue) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *ScalarValue) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *ScalarValue) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

func (x *ScalarValue) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

func (x *ScalarValue) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

func (x *ScalarValue) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

func (x *ScalarValue) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

func (x *ScalarValue) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

func (x *ScalarValue) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *ScalarValue) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *ScalarValue) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *ScalarValue) GetRepeatedDouble() []float64 {
	if x != nil {
		return x.RepeatedDouble
	}
	return nil
}

func (x *ScalarValue) GetRepeatedFloat() []float32 {
	if x != nil {
		return x.RepeatedFloat
	}
	return nil
}

func (x *ScalarValue) GetRepeatedInt32() []int32 {
	if x != nil {
		return x.RepeatedInt32
	}
	return nil
}

func (x *ScalarValue) GetRepeatedInt64() []int64 {
	if x != nil {
		return x.RepeatedInt64
	}
	return nil
}

func (x *ScalarValue) GetRepeatedUint32() []uint32 {
	if x != nil {
		return x.RepeatedUint32
	}
	return nil
}

func (x *ScalarValue) GetRepeatedUint64() []uint64 {
	if x != nil {
		return x.RepeatedUint64
	}
	return nil
}

func (x *ScalarValue) GetRepeatedSint32() []int32 {
	if x != nil {
		return x.RepeatedSint32
	}
	return nil
}

func (x *ScalarValue) GetRepeatedSint64() []int64 {
	if x != nil {
		return x.RepeatedSint64
	}
	return nil
}

func (x *ScalarValue) GetRepeatedFixed32() []uint32 {
	if x != nil {
		return x.RepeatedFixed32
	}
	return nil
}

func (x *ScalarValue) GetRepeatedFixed64() []uint64 {
	if x != nil {
		return x.RepeatedFixed64
	}
	return nil
}

func (x *ScalarValue) GetRepeatedSfixed32() []int32 {
	if x != nil {
		return x.RepeatedSfixed32
	}
	return nil
}

func (x *ScalarValue) GetRepeatedSfixed64() []int64 {
	if x != nil {
		return x.RepeatedSfixed64
	}
	return nil
}

func (x *ScalarValue) GetRepeatedBool() []bool {
	if x != nil {
		return x.RepeatedBool
	}
	return nil
}

func (x *ScalarValue) GetRepeatedString() []string {
	if x != nil {
		return x.RepeatedString
	}
	return nil
}

func (x *ScalarValue) GetRepeatedBytes() [][]byte {
	if x != nil {
		return x.RepeatedBytes
	}
	return nil
}

func (x *ScalarValue) GetRepeatedEnum() []FurType {
	if x != nil {
		return x.RepeatedEnum
	}
	return nil
}

func (x *ScalarValue) GetStringMap() map[string]string {
	if x != nil {
		return x.StringMap
	}
	return nil
}

func (x *ScalarValue) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ScalarValue) GetStrPtr() *wrapperspb.StringValue {
	if x != nil {
		return x.StrPtr
	}
	return nil
}

func (x *ScalarValue) GetBoolPtr() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolPtr
	}
	return nil
}

type EBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EBook) Reset() {
	*x = EBook{}
	mi := &file_models_animals_v1_animals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EBook) ProtoMessage() {}

func (x *EBook) ProtoReflect() protoreflect.Message {
	mi := &file_models_animals_v1_animals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EBook.ProtoReflect.Descriptor instead.
func (*EBook) Descriptor() ([]byte, []int) {
	return file_models_animals_v1_animals_proto_rawDescGZIP(), []int{2}
}

func (x *EBook) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PaperBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         int32                  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperBook) Reset() {
	*x = PaperBook{}
	mi := &file_models_animals_v1_animals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperBook) ProtoMessage() {}

func (x *PaperBook) ProtoReflect() protoreflect.Message {
	mi := &file_models_animals_v1_animals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperBook.ProtoReflect.Descriptor instead.
func (*PaperBook) Descriptor() ([]byte, []int) {
	return file_models_animals_v1_animals_proto_rawDescGZIP(), []int{3}
}

func (x *PaperBook) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type Book struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TenantId  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id        string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Types that are valid to be assigned to Medium:
	//
	//	*Book_Paper
	//	*Book_Ebook
	//	*Book_News
	Medium        isBook_Medium `protobuf_oneof:"medium"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_models_animals_v1_animals_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_models_animals_v1_animals_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_models_animals_v1_animals_proto_rawDescGZIP(), []int{4}
}

func (x *Book) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Book) GetMedium() isBook_Medium {
	if x != nil {
		return x.Medium
	}
	return nil
}

func (x *Book) GetPaper() *PaperBook {
	if x != nil {
		if x, ok := x.Medium.(*Book_Paper); ok {
			return x.Paper
		}
	}
	return nil
}

func (x *Book) GetEbook() *EBook {
	if x != nil {
		if x, ok := x.Medium.(*Book_Ebook); ok {
			return x.Ebook
		}
	}
	return nil
}

func (x *Book) GetNews() *Newspaper {
	if x != nil {
		if x, ok := x.Medium.(*Book_News); ok {
			return x.News
		}
	}
	return nil
}

type isBook_Medium interface {
	isBook_Medium()
}

type Book_Paper struct {
	Paper *PaperBook `protobuf:"bytes,50,opt,name=paper,proto3,oneof"`
}

type Book_Ebook struct {
	Ebook *EBook `protobuf:"bytes,51,opt,name=ebook,proto3,oneof"`
}

type Book_News struct {
	News *Newspaper `protobuf:"bytes,52,opt,name=news,proto3,oneof"`
}

func (*Book_Paper) isBook_Medium() {}

func (*Book_Ebook) isBook_Medium() {}

func (*Book_News) isBook_Medium() {}

type Newspaper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Newspaper) Reset() {
	*x = Newspaper{}
	mi := &file_models_animals_v1_animals_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Newspaper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Newspaper) ProtoMessage() {}

func (x *Newspaper) ProtoReflect() protoreflect.Message {
	mi := &file_models_animals_v1_animals_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Newspaper.ProtoReflect.Descriptor instead.
func (*Newspaper) Descriptor() ([]byte, []int) {
	return file_models_animals_v1_animals_proto_rawDescGZIP(), []int{5}
}

func (x *Newspaper) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Newspaper) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Newspaper) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_models_animals_v1_animals_proto protoreflect.FileDescriptor

const file_models_animals_v1_animals_proto_rawDesc = "" +
	"\n" +
	"\x1fmodels/animals/v1/animals.proto\x12\x11models.animals.v1\x1a\x16dynamo/v1/dynamo.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x12pgdb/v1/pgdb.proto\"\xa5\x06\n" +
	"\x03Pet\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x02id\x18\x02 \x01(\tB\x06\xd2\xf7\x02\x02\b\x01R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12+\n" +
	"\fdisplay_name\x18\x06 \x01(\tB\b\xd2\xf7\x02\x04\b\x02\x10\x03R\vdisplayName\x12(\n" +
	"\vdescription\x18\a \x01(\tB\x06\xd2\xf7\x02\x02\b\x02R\vdescription\x12%\n" +
	"\x0esystem_builtin\x18\t \x01(\bR\rsystemBuiltin\x123\n" +
	"\aelapsed\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\aelapsed\x121\n" +
	"\aprofile\x18\v \x01(\v2\x17.google.protobuf.StructR\aprofile\x12\x1a\n" +
	"\bcuteness\x18\f \x01(\x02R\bcuteness\x12\x14\n" +
	"\x05price\x18\r \x01(\x01R\x05price\x12\x9a\x01\n" +
	"Ivery_long_naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaame\x18\x0e \x01(\bRGveryLongNaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaame\x12>\n" +
	"\x0eextra_profiles\x18\x0f \x03(\v2\x17.google.protobuf.StructR\rextraProfiles:C\x82\xf7\x02\x1a\x12\x18\n" +
	"\ttenant_id\n" +
	"\x02id\x1a\aexample\xd2\xf7\x02!\x12\x1f\n" +
	"\aprofile\x10\x03\x1a\ttenant_id\x1a\aprofile\"\xac\f\n" +
	"\vScalarValue\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06double\x18\x03 \x01(\x01R\x06double\x12\x14\n" +
	"\x05float\x18\x04 \x01(\x02R\x05float\x12\x14\n" +
	"\x05int32\x18\x05 \x01(\x05R\x05int32\x12\x14\n" +
	"\x05int64\x18\x06 \x01(\x03R\x05int64\x12\x16\n" +
	"\x06uint32\x18\a \x01(\rR\x06uint32\x12\x16\n" +
	"\x06uint64\x18\b \x01(\x04R\x06uint64\x12\x16\n" +
	"\x06sint32\x18\t \x01(\x11R\x06sint32\x12\x16\n" +
	"\x06sint64\x18\n" +
	" \x01(\x12R\x06sint64\x12\x18\n" +
	"\afixed32\x18\v \x01(\aR\afixed32\x12\x18\n" +
	"\afixed64\x18\f \x01(\x06R\afixed64\x12\x1a\n" +
	"\bsfixed32\x18\r \x01(\x0fR\bsfixed32\x12\x1a\n" +
	"\bsfixed64\x18\x0e \x01(\x10R\bsfixed64\x12\x12\n" +
	"\x04bool\x18\x0f \x01(\bR\x04bool\x12 \n" +
	"\x06string\x18\x10 \x01(\tB\b\xd2\xf7\x02\x04\b\x02\x10\x03R\x06string\x12\x14\n" +
	"\x05bytes\x18\x11 \x01(\fR\x05bytes\x12'\n" +
	"\x0frepeated_double\x18\x17 \x03(\x01R\x0erepeatedDouble\x12%\n" +
	"\x0erepeated_float\x18\x18 \x03(\x02R\rrepeatedFloat\x12%\n" +
	"\x0erepeated_int32\x18\x19 \x03(\x05R\rrepeatedInt32\x12%\n" +
	"\x0erepeated_int64\x18\x1a \x03(\x03R\rrepeatedInt64\x12'\n" +
	"\x0frepeated_uint32\x18\x1b \x03(\rR\x0erepeatedUint32\x12'\n" +
	"\x0frepeated_uint64\x18\x1c \x03(\x04R\x0erepeatedUint64\x12'\n" +
	"\x0frepeated_sint32\x18\x1d \x03(\x11R\x0erepeatedSint32\x12'\n" +
	"\x0frepeated_sint64\x18\x1e \x03(\x12R\x0erepeatedSint64\x12)\n" +
	"\x10repeated_fixed32\x18\x1f \x03(\aR\x0frepeatedFixed32\x12)\n" +
	"\x10repeated_fixed64\x18  \x03(\x06R\x0frepeatedFixed64\x12+\n" +
	"\x11repeated_sfixed32\x18! \x03(\x0fR\x10repeatedSfixed32\x12+\n" +
	"\x11repeated_sfixed64\x18\" \x03(\x10R\x10repeatedSfixed64\x12#\n" +
	"\rrepeated_bool\x18# \x03(\bR\frepeatedBool\x121\n" +
	"\x0frepeated_string\x18$ \x03(\tB\b\xd2\xf7\x02\x04\b\x02\x10\x03R\x0erepeatedString\x12%\n" +
	"\x0erepeated_bytes\x18% \x03(\fR\rrepeatedBytes\x12?\n" +
	"\rrepeated_enum\x18& \x03(\x0e2\x1a.models.animals.v1.FurTypeR\frepeatedEnum\x12T\n" +
	"\n" +
	"string_map\x18' \x03(\v2-.models.animals.v1.ScalarValue.StringMapEntryB\x06\xd2\xf7\x02\x02\x18\x03R\tstringMap\x129\n" +
	"\n" +
	"created_at\x18( \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x125\n" +
	"\astr_ptr\x18d \x01(\v2\x1c.google.protobuf.StringValueR\x06strPtr\x125\n" +
	"\bbool_ptr\x18e \x01(\v2\x1a.google.protobuf.BoolValueR\aboolPtr\x1a<\n" +
	"\x0eStringMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x8e\x01\x82\xf7\x02\x11\x12\x0f\n" +
	"\ttenant_id\x12\x02id\xd2\xf7\x02u\x12s\n" +
	"\x11repeated_sfixed32\x10\x02\x1a\ttenant_id\x1a\x11repeated_sfixed32\x1a\x11repeated_sfixed64\x1a\x0frepeated_double\x1a\x0erepeated_bytes\x1a\n" +
	"string_map\"#\n" +
	"\x05EBook\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size:\x06\xd2\xf7\x02\x02 \x01\")\n" +
	"\tPaperBook\x12\x14\n" +
	"\x05pages\x18\x02 \x01(\x05R\x05pages:\x06\xd2\xf7\x02\x02 \x01\"\xbc\x02\n" +
	"\x04Book\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x02id\x18\x02 \x01(\tB\x06\xd2\xf7\x02\x02\b\x01R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x124\n" +
	"\x05paper\x182 \x01(\v2\x1c.models.animals.v1.PaperBookH\x00R\x05paper\x120\n" +
	"\x05ebook\x183 \x01(\v2\x18.models.animals.v1.EBookH\x00R\x05ebook\x122\n" +
	"\x04news\x184 \x01(\v2\x1c.models.animals.v1.NewspaperH\x00R\x04news:\x1e\x82\xf7\x02\x1a\x12\x18\n" +
	"\ttenant_id\n" +
	"\x02id\x1a\aexampleB\b\n" +
	"\x06medium\"\x87\x01\n" +
	"\tNewspaper\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt:\x1b\x82\xf7\x02\x0f\x12\r\n" +
	"\x02id\x1a\aexample\xd2\xf7\x02\x04\x1a\x02id*I\n" +
	"\aFurType\x12\x18\n" +
	"\x14FUR_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rFUR_TYPE_NONE\x10\x01\x12\x11\n" +
	"\rFUR_TYPE_LOTS\x10\x02B>Z<github.com/ductone/protoc-gen-pgdb/example/models/animals/v1b\x06proto3"

var (
	file_models_animals_v1_animals_proto_rawDescOnce sync.Once
	file_models_animals_v1_animals_proto_rawDescData []byte
)

func file_models_animals_v1_animals_proto_rawDescGZIP() []byte {
	file_models_animals_v1_animals_proto_rawDescOnce.Do(func() {
		file_models_animals_v1_animals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_animals_v1_animals_proto_rawDesc), len(file_models_animals_v1_animals_proto_rawDesc)))
	})
	return file_models_animals_v1_animals_proto_rawDescData
}

var file_models_animals_v1_animals_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_animals_v1_animals_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_models_animals_v1_animals_proto_goTypes = []any{
	(FurType)(0),                   // 0: models.animals.v1.FurType
	(*Pet)(nil),                    // 1: models.animals.v1.Pet
	(*ScalarValue)(nil),            // 2: models.animals.v1.ScalarValue
	(*EBook)(nil),                  // 3: models.animals.v1.EBook
	(*PaperBook)(nil),              // 4: models.animals.v1.PaperBook
	(*Book)(nil),                   // 5: models.animals.v1.Book
	(*Newspaper)(nil),              // 6: models.animals.v1.Newspaper
	nil,                            // 7: models.animals.v1.ScalarValue.StringMapEntry
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 9: google.protobuf.Duration
	(*structpb.Struct)(nil),        // 10: google.protobuf.Struct
	(*wrapperspb.StringValue)(nil), // 11: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),   // 12: google.protobuf.BoolValue
}
var file_models_animals_v1_animals_proto_depIdxs = []int32{
	8,  // 0: models.animals.v1.Pet.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: models.animals.v1.Pet.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: models.animals.v1.Pet.deleted_at:type_name -> google.protobuf.Timestamp
	9,  // 3: models.animals.v1.Pet.elapsed:type_name -> google.protobuf.Duration
	10, // 4: models.animals.v1.Pet.profile:type_name -> google.protobuf.Struct
	10, // 5: models.animals.v1.Pet.extra_profiles:type_name -> google.protobuf.Struct
	0,  // 6: models.animals.v1.ScalarValue.repeated_enum:type_name -> models.animals.v1.FurType
	7,  // 7: models.animals.v1.ScalarValue.string_map:type_name -> models.animals.v1.ScalarValue.StringMapEntry
	8,  // 8: models.animals.v1.ScalarValue.created_at:type_name -> google.protobuf.Timestamp
	11, // 9: models.animals.v1.ScalarValue.str_ptr:type_name -> google.protobuf.StringValue
	12, // 10: models.animals.v1.ScalarValue.bool_ptr:type_name -> google.protobuf.BoolValue
	8,  // 11: models.animals.v1.Book.created_at:type_name -> google.protobuf.Timestamp
	4,  // 12: models.animals.v1.Book.paper:type_name -> models.animals.v1.PaperBook
	3,  // 13: models.animals.v1.Book.ebook:type_name -> models.animals.v1.EBook
	6,  // 14: models.animals.v1.Book.news:type_name -> models.animals.v1.Newspaper
	8,  // 15: models.animals.v1.Newspaper.created_at:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_models_animals_v1_animals_proto_init() }
func file_models_animals_v1_animals_proto_init() {
	if File_models_animals_v1_animals_proto != nil {
		return
	}
	file_models_animals_v1_animals_proto_msgTypes[4].OneofWrappers = []any{
		(*Book_Paper)(nil),
		(*Book_Ebook)(nil),
		(*Book_News)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_animals_v1_animals_proto_rawDesc), len(file_models_animals_v1_animals_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_animals_v1_animals_proto_goTypes,
		DependencyIndexes: file_models_animals_v1_animals_proto_depIdxs,
		EnumInfos:         file_models_animals_v1_animals_proto_enumTypes,
		MessageInfos:      file_models_animals_v1_animals_proto_msgTypes,
	}.Build()
	File_models_animals_v1_animals_proto = out.File
	file_models_animals_v1_animals_proto_goTypes = nil
	file_models_animals_v1_animals_proto_depIdxs = nil
}
