// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: models/llm/v1/models.proto

package v1

import (
	_ "github.com/ductone/protoc-gen-pgdb/pgdb/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Map model embedding to their own columns
// for each model embedding, add a column to the table
// xxx_embedding_1
// xxx_embedding_2
// etc for each enum value
// testing
type Model int32

const (
	Model_MODEL_UNSPECIFIED Model = 0
	Model_MODEL_3DIMS       Model = 1
	Model_MODEL_4DIMS       Model = 2
)

// Enum value maps for Model.
var (
	Model_name = map[int32]string{
		0: "MODEL_UNSPECIFIED",
		1: "MODEL_3DIMS",
		2: "MODEL_4DIMS",
	}
	Model_value = map[string]int32{
		"MODEL_UNSPECIFIED": 0,
		"MODEL_3DIMS":       1,
		"MODEL_4DIMS":       2,
	}
)

func (x Model) Enum() *Model {
	p := new(Model)
	*p = x
	return p
}

func (x Model) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Model) Descriptor() protoreflect.EnumDescriptor {
	return file_models_llm_v1_models_proto_enumTypes[0].Descriptor()
}

func (Model) Type() protoreflect.EnumType {
	return &file_models_llm_v1_models_proto_enumTypes[0]
}

func (x Model) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Model.Descriptor instead.
func (Model) EnumDescriptor() ([]byte, []int) {
	return file_models_llm_v1_models_proto_rawDescGZIP(), []int{0}
}

var File_models_llm_v1_models_proto protoreflect.FileDescriptor

var file_models_llm_v1_models_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6c, 0x6c, 0x6d, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x76, 0x31, 0x1a, 0x12, 0x70, 0x67, 0x64,
	0x62, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x67, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a,
	0x50, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x4f, 0x44, 0x45,
	0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x17, 0x0a, 0x0b, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x33, 0x44, 0x49, 0x4d, 0x53, 0x10, 0x01,
	0x1a, 0x06, 0xd2, 0xf7, 0x02, 0x02, 0x08, 0x03, 0x12, 0x17, 0x0a, 0x0b, 0x4d, 0x4f, 0x44, 0x45,
	0x4c, 0x5f, 0x34, 0x44, 0x49, 0x4d, 0x53, 0x10, 0x02, 0x1a, 0x06, 0xd2, 0xf7, 0x02, 0x02, 0x08,
	0x04, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x75, 0x63, 0x74, 0x6f, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67,
	0x65, 0x6e, 0x2d, 0x70, 0x67, 0x64, 0x62, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6c, 0x6c, 0x6d, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_llm_v1_models_proto_rawDescOnce sync.Once
	file_models_llm_v1_models_proto_rawDescData = file_models_llm_v1_models_proto_rawDesc
)

func file_models_llm_v1_models_proto_rawDescGZIP() []byte {
	file_models_llm_v1_models_proto_rawDescOnce.Do(func() {
		file_models_llm_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_llm_v1_models_proto_rawDescData)
	})
	return file_models_llm_v1_models_proto_rawDescData
}

var file_models_llm_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_llm_v1_models_proto_goTypes = []interface{}{
	(Model)(0), // 0: models.llm.v1.Model
}
var file_models_llm_v1_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_llm_v1_models_proto_init() }
func file_models_llm_v1_models_proto_init() {
	if File_models_llm_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_llm_v1_models_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_llm_v1_models_proto_goTypes,
		DependencyIndexes: file_models_llm_v1_models_proto_depIdxs,
		EnumInfos:         file_models_llm_v1_models_proto_enumTypes,
	}.Build()
	File_models_llm_v1_models_proto = out.File
	file_models_llm_v1_models_proto_rawDesc = nil
	file_models_llm_v1_models_proto_goTypes = nil
	file_models_llm_v1_models_proto_depIdxs = nil
}
