// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: models/food/v1/food.proto

package v1

import (
	v1 "github.com/ductone/protoc-gen-pgdb/example/models/llm/v1"
	_ "github.com/ductone/protoc-gen-pgdb/pgdb/v1"
	_ "github.com/pquerna/protoc-gen-dynamo/dynamo/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pasta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pasta) Reset() {
	*x = Pasta{}
	mi := &file_models_food_v1_food_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pasta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pasta) ProtoMessage() {}

func (x *Pasta) ProtoReflect() protoreflect.Message {
	mi := &file_models_food_v1_food_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pasta.ProtoReflect.Descriptor instead.
func (*Pasta) Descriptor() ([]byte, []int) {
	return file_models_food_v1_food_proto_rawDescGZIP(), []int{0}
}

func (x *Pasta) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Pasta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pasta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Pasta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Pasta) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type PastaIngredient struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TenantId     string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IngredientId string                 `protobuf:"bytes,2,opt,name=ingredient_id,json=ingredientId,proto3" json:"ingredient_id,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	PastaId      string                 `protobuf:"bytes,6,opt,name=pasta_id,json=pastaId,proto3" json:"pasta_id,omitempty"`
	Id           string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	// We want to verify
	// 1. Type is repeated
	// 2. Type is a nested message
	// 3. Message type has 2 fields, enum type and repeated float type
	ModelEmbeddings []*PastaIngredient_ModelEmbedding `protobuf:"bytes,8,rep,name=model_embeddings,json=modelEmbeddings,proto3" json:"model_embeddings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PastaIngredient) Reset() {
	*x = PastaIngredient{}
	mi := &file_models_food_v1_food_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PastaIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PastaIngredient) ProtoMessage() {}

func (x *PastaIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_models_food_v1_food_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PastaIngredient.ProtoReflect.Descriptor instead.
func (*PastaIngredient) Descriptor() ([]byte, []int) {
	return file_models_food_v1_food_proto_rawDescGZIP(), []int{1}
}

func (x *PastaIngredient) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PastaIngredient) GetIngredientId() string {
	if x != nil {
		return x.IngredientId
	}
	return ""
}

func (x *PastaIngredient) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PastaIngredient) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PastaIngredient) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *PastaIngredient) GetPastaId() string {
	if x != nil {
		return x.PastaId
	}
	return ""
}

func (x *PastaIngredient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PastaIngredient) GetModelEmbeddings() []*PastaIngredient_ModelEmbedding {
	if x != nil {
		return x.ModelEmbeddings
	}
	return nil
}

type SauceIngredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	SourceAddr    string                 `protobuf:"bytes,6,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SauceIngredient) Reset() {
	*x = SauceIngredient{}
	mi := &file_models_food_v1_food_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SauceIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SauceIngredient) ProtoMessage() {}

func (x *SauceIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_models_food_v1_food_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SauceIngredient.ProtoReflect.Descriptor instead.
func (*SauceIngredient) Descriptor() ([]byte, []int) {
	return file_models_food_v1_food_proto_rawDescGZIP(), []int{2}
}

func (x *SauceIngredient) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SauceIngredient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SauceIngredient) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SauceIngredient) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SauceIngredient) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *SauceIngredient) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

type GarlicIngredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	SourceAddr    string                 `protobuf:"bytes,6,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GarlicIngredient) Reset() {
	*x = GarlicIngredient{}
	mi := &file_models_food_v1_food_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GarlicIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarlicIngredient) ProtoMessage() {}

func (x *GarlicIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_models_food_v1_food_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GarlicIngredient.ProtoReflect.Descriptor instead.
func (*GarlicIngredient) Descriptor() ([]byte, []int) {
	return file_models_food_v1_food_proto_rawDescGZIP(), []int{3}
}

func (x *GarlicIngredient) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GarlicIngredient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GarlicIngredient) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GarlicIngredient) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GarlicIngredient) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *GarlicIngredient) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

type CheeseIngredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // KSUID field for partitioning
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	SourceAddr    string                 `protobuf:"bytes,6,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheeseIngredient) Reset() {
	*x = CheeseIngredient{}
	mi := &file_models_food_v1_food_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheeseIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheeseIngredient) ProtoMessage() {}

func (x *CheeseIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_models_food_v1_food_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheeseIngredient.ProtoReflect.Descriptor instead.
func (*CheeseIngredient) Descriptor() ([]byte, []int) {
	return file_models_food_v1_food_proto_rawDescGZIP(), []int{4}
}

func (x *CheeseIngredient) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheeseIngredient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheeseIngredient) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CheeseIngredient) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CheeseIngredient) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *CheeseIngredient) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

type PastaIngredient_ModelEmbedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         v1.Model               `protobuf:"varint,1,opt,name=model,proto3,enum=models.llm.v1.Model" json:"model,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PastaIngredient_ModelEmbedding) Reset() {
	*x = PastaIngredient_ModelEmbedding{}
	mi := &file_models_food_v1_food_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PastaIngredient_ModelEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PastaIngredient_ModelEmbedding) ProtoMessage() {}

func (x *PastaIngredient_ModelEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_models_food_v1_food_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PastaIngredient_ModelEmbedding.ProtoReflect.Descriptor instead.
func (*PastaIngredient_ModelEmbedding) Descriptor() ([]byte, []int) {
	return file_models_food_v1_food_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PastaIngredient_ModelEmbedding) GetModel() v1.Model {
	if x != nil {
		return x.Model
	}
	return v1.Model(0)
}

func (x *PastaIngredient_ModelEmbedding) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

var File_models_food_v1_food_proto protoreflect.FileDescriptor

const file_models_food_v1_food_proto_rawDesc = "" +
	"\n" +
	"\x19models/food/v1/food.proto\x12\x0emodels.food.v1\x1a\x16dynamo/v1/dynamo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1amodels/llm/v1/models.proto\x1a\x12pgdb/v1/pgdb.proto\"\x93\x02\n" +
	"\x05Pasta\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x02id\x18\x02 \x01(\tB\x06\xd2\xf7\x02\x02\b\x01R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt:$\x82\xf7\x02\x1a\x12\x18\n" +
	"\ttenant_id\n" +
	"\x02id\x1a\aexample\xd2\xf7\x02\x02(\x01\"\xc7\x06\n" +
	"\x0fPastaIngredient\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\ringredient_id\x18\x02 \x01(\tR\fingredientId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12!\n" +
	"\bpasta_id\x18\x06 \x01(\tB\x06\xd2\xf7\x02\x02\b\x01R\apastaId\x12\x16\n" +
	"\x02id\x18\a \x01(\tB\x06\xd2\xf7\x02\x02\b\x01R\x02id\x12a\n" +
	"\x10model_embeddings\x18\b \x03(\v2..models.food.v1.PastaIngredient.ModelEmbeddingB\x06\xd2\xf7\x02\x02\x18\x04R\x0fmodelEmbeddings\x1ab\n" +
	"\x0eModelEmbedding\x12*\n" +
	"\x05model\x18\x01 \x01(\x0e2\x14.models.llm.v1.ModelR\x05model\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding:\x06\xd2\xf7\x02\x02 \x01:\xbe\x02\x82\xf7\x02=\x12;\n" +
	"\ttenant_id\n" +
	"\bpasta_id\n" +
	"\ringredient_id\n" +
	"\x02id\x1a\x11exampleingredient\xd2\xf7\x02\xf8\x01\x12#\n" +
	"\x06pastas\x10\x01\x1a\ttenant_id\x1a\bpasta_id\x1a\x02id\x12-\n" +
	"\vingredients\x10\x01\x1a\ttenant_id\x1a\ringredient_id\x1a\x02id\x12.\n" +
	"\reverythingggg\x10\x01\x1a\ringredient_id\x1a\bpasta_id\x1a\x02id\x12;\n" +
	"\x18everythingggg_alive_only\x10\x01\x1a\ringredient_id\x1a\bpasta_id\x1a\x02id(\x01(\x0123\n" +
	"\x17tenant_id_ingredient_id\x1a\ttenant_id\x1a\ringredient_id\"\xf8\x02\n" +
	"\x0fSauceIngredient\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x02id\x18\x02 \x01(\tB\x06\xd2\xf7\x02\x02\b\x01R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12'\n" +
	"\vsource_addr\x18\x06 \x01(\tB\x06\xd2\xf7\x02\x02\x18\x05R\n" +
	"sourceAddr:V\x82\xf7\x02\x1f\x12\x1d\n" +
	"\ttenant_id\n" +
	"\x02id\x1a\fexamplesauce\xd2\xf7\x02/\x12-\n" +
	"\x11source_addr_index\x10\x01\x1a\ttenant_id\x1a\vsource_addr\"\xfe\x02\n" +
	"\x10GarlicIngredient\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x02id\x18\x02 \x01(\tB\x06\xd2\xf7\x02\x02\b\x01R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12'\n" +
	"\vsource_addr\x18\x06 \x01(\tB\x06\xd2\xf7\x02\x02\x18\x05R\n" +
	"sourceAddr:[\x82\xf7\x02 \x12\x1e\n" +
	"\ttenant_id\n" +
	"\x02id\x1a\rexamplecheese\xd2\xf7\x023\x12-\n" +
	"\x11source_addr_index\x10\x01\x1a\ttenant_id\x1a\vsource_addr8\x01@\x02\"\xe8\x02\n" +
	"\x10CheeseIngredient\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x02id\x18\x02 \x01(\tB\x06\xd2\xf7\x02\x02\b\x01R\x02id\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12'\n" +
	"\vsource_addr\x18\x06 \x01(\tB\x06\xd2\xf7\x02\x02\x18\x05R\n" +
	"sourceAddr:e\x82\xf7\x02 \x12\x1e\n" +
	"\ttenant_id\n" +
	"\x02id\x1a\rexamplecheese\xd2\xf7\x02=\x12-\n" +
	"\x11source_addr_index\x10\x01\x1a\ttenant_id\x1a\vsource_addr@\x02J\bevent_idP\x01B;Z9github.com/ductone/protoc-gen-pgdb/example/models/food/v1b\x06proto3"

var (
	file_models_food_v1_food_proto_rawDescOnce sync.Once
	file_models_food_v1_food_proto_rawDescData []byte
)

func file_models_food_v1_food_proto_rawDescGZIP() []byte {
	file_models_food_v1_food_proto_rawDescOnce.Do(func() {
		file_models_food_v1_food_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_food_v1_food_proto_rawDesc), len(file_models_food_v1_food_proto_rawDesc)))
	})
	return file_models_food_v1_food_proto_rawDescData
}

var file_models_food_v1_food_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_models_food_v1_food_proto_goTypes = []any{
	(*Pasta)(nil),                          // 0: models.food.v1.Pasta
	(*PastaIngredient)(nil),                // 1: models.food.v1.PastaIngredient
	(*SauceIngredient)(nil),                // 2: models.food.v1.SauceIngredient
	(*GarlicIngredient)(nil),               // 3: models.food.v1.GarlicIngredient
	(*CheeseIngredient)(nil),               // 4: models.food.v1.CheeseIngredient
	(*PastaIngredient_ModelEmbedding)(nil), // 5: models.food.v1.PastaIngredient.ModelEmbedding
	(*timestamppb.Timestamp)(nil),          // 6: google.protobuf.Timestamp
	(v1.Model)(0),                          // 7: models.llm.v1.Model
}
var file_models_food_v1_food_proto_depIdxs = []int32{
	6,  // 0: models.food.v1.Pasta.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: models.food.v1.Pasta.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: models.food.v1.Pasta.deleted_at:type_name -> google.protobuf.Timestamp
	6,  // 3: models.food.v1.PastaIngredient.created_at:type_name -> google.protobuf.Timestamp
	6,  // 4: models.food.v1.PastaIngredient.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 5: models.food.v1.PastaIngredient.deleted_at:type_name -> google.protobuf.Timestamp
	5,  // 6: models.food.v1.PastaIngredient.model_embeddings:type_name -> models.food.v1.PastaIngredient.ModelEmbedding
	6,  // 7: models.food.v1.SauceIngredient.created_at:type_name -> google.protobuf.Timestamp
	6,  // 8: models.food.v1.SauceIngredient.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 9: models.food.v1.SauceIngredient.deleted_at:type_name -> google.protobuf.Timestamp
	6,  // 10: models.food.v1.GarlicIngredient.created_at:type_name -> google.protobuf.Timestamp
	6,  // 11: models.food.v1.GarlicIngredient.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 12: models.food.v1.GarlicIngredient.deleted_at:type_name -> google.protobuf.Timestamp
	6,  // 13: models.food.v1.CheeseIngredient.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 14: models.food.v1.CheeseIngredient.deleted_at:type_name -> google.protobuf.Timestamp
	7,  // 15: models.food.v1.PastaIngredient.ModelEmbedding.model:type_name -> models.llm.v1.Model
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_models_food_v1_food_proto_init() }
func file_models_food_v1_food_proto_init() {
	if File_models_food_v1_food_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_food_v1_food_proto_rawDesc), len(file_models_food_v1_food_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_food_v1_food_proto_goTypes,
		DependencyIndexes: file_models_food_v1_food_proto_depIdxs,
		MessageInfos:      file_models_food_v1_food_proto_msgTypes,
	}.Build()
	File_models_food_v1_food_proto = out.File
	file_models_food_v1_food_proto_goTypes = nil
	file_models_food_v1_food_proto_depIdxs = nil
}
