// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: models/city/v1/city.proto

package v1

import (
	v11 "github.com/ductone/protoc-gen-pgdb/example/models/animals/v1"
	v1 "github.com/ductone/protoc-gen-pgdb/example/models/zoo/v1"
	_ "github.com/ductone/protoc-gen-pgdb/pgdb/v1"
	_ "github.com/pquerna/protoc-gen-dynamo/dynamo/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attractions struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Id        string                 `protobuf:"bytes,2,opt,name=id,proto3"`
	xxx_hidden_Numid     int32                  `protobuf:"varint,3,opt,name=numid,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_What      isAttractions_What     `protobuf_oneof:"what"`
	xxx_hidden_Medium    *v1.Shop               `protobuf:"bytes,12,opt,name=medium,proto3"`
	xxx_hidden_Config    *AttractionsConfig     `protobuf:"bytes,13,opt,name=config,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Attractions) Reset() {
	*x = Attractions{}
	mi := &file_models_city_v1_city_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attractions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attractions) ProtoMessage() {}

func (x *Attractions) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Attractions) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *Attractions) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Attractions) GetNumid() int32 {
	if x != nil {
		return x.xxx_hidden_Numid
	}
	return 0
}

func (x *Attractions) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Attractions) GetPet() *v11.Pet {
	if x != nil {
		if x, ok := x.xxx_hidden_What.(*attractions_Pet); ok {
			return x.Pet
		}
	}
	return nil
}

func (x *Attractions) GetZooShop() *v1.Shop {
	if x != nil {
		if x, ok := x.xxx_hidden_What.(*attractions_ZooShop); ok {
			return x.ZooShop
		}
	}
	return nil
}

func (x *Attractions) GetMedium() *v1.Shop {
	if x != nil {
		return x.xxx_hidden_Medium
	}
	return nil
}

func (x *Attractions) GetConfig() *AttractionsConfig {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *Attractions) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *Attractions) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Attractions) SetNumid(v int32) {
	x.xxx_hidden_Numid = v
}

func (x *Attractions) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Attractions) SetPet(v *v11.Pet) {
	if v == nil {
		x.xxx_hidden_What = nil
		return
	}
	x.xxx_hidden_What = &attractions_Pet{v}
}

func (x *Attractions) SetZooShop(v *v1.Shop) {
	if v == nil {
		x.xxx_hidden_What = nil
		return
	}
	x.xxx_hidden_What = &attractions_ZooShop{v}
}

func (x *Attractions) SetMedium(v *v1.Shop) {
	x.xxx_hidden_Medium = v
}

func (x *Attractions) SetConfig(v *AttractionsConfig) {
	x.xxx_hidden_Config = v
}

func (x *Attractions) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Attractions) HasWhat() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_What != nil
}

func (x *Attractions) HasPet() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_What.(*attractions_Pet)
	return ok
}

func (x *Attractions) HasZooShop() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_What.(*attractions_ZooShop)
	return ok
}

func (x *Attractions) HasMedium() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Medium != nil
}

func (x *Attractions) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *Attractions) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Attractions) ClearWhat() {
	x.xxx_hidden_What = nil
}

func (x *Attractions) ClearPet() {
	if _, ok := x.xxx_hidden_What.(*attractions_Pet); ok {
		x.xxx_hidden_What = nil
	}
}

func (x *Attractions) ClearZooShop() {
	if _, ok := x.xxx_hidden_What.(*attractions_ZooShop); ok {
		x.xxx_hidden_What = nil
	}
}

func (x *Attractions) ClearMedium() {
	x.xxx_hidden_Medium = nil
}

func (x *Attractions) ClearConfig() {
	x.xxx_hidden_Config = nil
}

const Attractions_What_not_set_case case_Attractions_What = 0
const Attractions_Pet_case case_Attractions_What = 10
const Attractions_ZooShop_case case_Attractions_What = 11

func (x *Attractions) WhichWhat() case_Attractions_What {
	if x == nil {
		return Attractions_What_not_set_case
	}
	switch x.xxx_hidden_What.(type) {
	case *attractions_Pet:
		return Attractions_Pet_case
	case *attractions_ZooShop:
		return Attractions_ZooShop_case
	default:
		return Attractions_What_not_set_case
	}
}

type Attractions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId  string
	Id        string
	Numid     int32
	CreatedAt *timestamppb.Timestamp
	// Fields of oneof xxx_hidden_What:
	Pet     *v11.Pet
	ZooShop *v1.Shop
	// -- end of xxx_hidden_What
	Medium *v1.Shop
	// This field tests the nested_only collision fix:
	// "Attractions" + "Config" = "AttractionsConfig" (same as the message type name)
	// Without the fix, this would cause duplicate type definitions.
	Config *AttractionsConfig
}

func (b0 Attractions_builder) Build() *Attractions {
	m0 := &Attractions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Numid = b.Numid
	x.xxx_hidden_CreatedAt = b.CreatedAt
	if b.Pet != nil {
		x.xxx_hidden_What = &attractions_Pet{b.Pet}
	}
	if b.ZooShop != nil {
		x.xxx_hidden_What = &attractions_ZooShop{b.ZooShop}
	}
	x.xxx_hidden_Medium = b.Medium
	x.xxx_hidden_Config = b.Config
	return m0
}

type case_Attractions_What protoreflect.FieldNumber

func (x case_Attractions_What) String() string {
	md := file_models_city_v1_city_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAttractions_What interface {
	isAttractions_What()
}

type attractions_Pet struct {
	Pet *v11.Pet `protobuf:"bytes,10,opt,name=pet,proto3,oneof"`
}

type attractions_ZooShop struct {
	ZooShop *v1.Shop `protobuf:"bytes,11,opt,name=zoo_shop,json=zooShop,proto3,oneof"`
}

func (*attractions_Pet) isAttractions_What() {}

func (*attractions_ZooShop) isAttractions_What() {}

// A top-level nested_only message with a nested sub-message.
// Named to collide when embedded in Attractions: "Attractions" + "Config" = "AttractionsConfig"
type AttractionsConfig struct {
	state             protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Detail *AttractionsConfig_Detail `protobuf:"bytes,1,opt,name=detail,proto3"`
	xxx_hidden_Name   string                    `protobuf:"bytes,2,opt,name=name,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttractionsConfig) Reset() {
	*x = AttractionsConfig{}
	mi := &file_models_city_v1_city_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttractionsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttractionsConfig) ProtoMessage() {}

func (x *AttractionsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AttractionsConfig) GetDetail() *AttractionsConfig_Detail {
	if x != nil {
		return x.xxx_hidden_Detail
	}
	return nil
}

func (x *AttractionsConfig) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *AttractionsConfig) SetDetail(v *AttractionsConfig_Detail) {
	x.xxx_hidden_Detail = v
}

func (x *AttractionsConfig) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *AttractionsConfig) HasDetail() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Detail != nil
}

func (x *AttractionsConfig) ClearDetail() {
	x.xxx_hidden_Detail = nil
}

type AttractionsConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Detail *AttractionsConfig_Detail
	Name   string
}

func (b0 AttractionsConfig_builder) Build() *AttractionsConfig {
	m0 := &AttractionsConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Detail = b.Detail
	x.xxx_hidden_Name = b.Name
	return m0
}

// A second parent that also embeds AttractionsConfig (tests multi-embed scenario).
// "AttractionsV2" + "Config" = "AttractionsV2Config" which does NOT collide with "AttractionsConfig".
type AttractionsV2 struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Id        string                 `protobuf:"bytes,2,opt,name=id,proto3"`
	xxx_hidden_Config    *AttractionsConfig     `protobuf:"bytes,3,opt,name=config,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AttractionsV2) Reset() {
	*x = AttractionsV2{}
	mi := &file_models_city_v1_city_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttractionsV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttractionsV2) ProtoMessage() {}

func (x *AttractionsV2) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AttractionsV2) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *AttractionsV2) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *AttractionsV2) GetConfig() *AttractionsConfig {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *AttractionsV2) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *AttractionsV2) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *AttractionsV2) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *AttractionsV2) SetConfig(v *AttractionsConfig) {
	x.xxx_hidden_Config = v
}

func (x *AttractionsV2) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *AttractionsV2) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *AttractionsV2) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *AttractionsV2) ClearConfig() {
	x.xxx_hidden_Config = nil
}

func (x *AttractionsV2) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type AttractionsV2_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId  string
	Id        string
	Config    *AttractionsConfig
	CreatedAt *timestamppb.Timestamp
}

func (b0 AttractionsV2_builder) Build() *AttractionsV2 {
	m0 := &AttractionsV2{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Config = b.Config
	x.xxx_hidden_CreatedAt = b.CreatedAt
	return m0
}

// Test case for nested_only message with oneof embedded through multiple layers.
// This reproduces a bug where unsafe query builder children have wrong ParentTypeName.
type NestedOnlyWithOneof struct {
	state               protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Selector isNestedOnlyWithOneof_Selector `protobuf_oneof:"selector"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NestedOnlyWithOneof) Reset() {
	*x = NestedOnlyWithOneof{}
	mi := &file_models_city_v1_city_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedOnlyWithOneof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedOnlyWithOneof) ProtoMessage() {}

func (x *NestedOnlyWithOneof) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NestedOnlyWithOneof) GetChoiceA() *NestedOnlyWithOneof_ChoiceA {
	if x != nil {
		if x, ok := x.xxx_hidden_Selector.(*nestedOnlyWithOneof_ChoiceA_); ok {
			return x.ChoiceA
		}
	}
	return nil
}

func (x *NestedOnlyWithOneof) GetChoiceB() *NestedOnlyWithOneof_ChoiceB {
	if x != nil {
		if x, ok := x.xxx_hidden_Selector.(*nestedOnlyWithOneof_ChoiceB_); ok {
			return x.ChoiceB
		}
	}
	return nil
}

func (x *NestedOnlyWithOneof) SetChoiceA(v *NestedOnlyWithOneof_ChoiceA) {
	if v == nil {
		x.xxx_hidden_Selector = nil
		return
	}
	x.xxx_hidden_Selector = &nestedOnlyWithOneof_ChoiceA_{v}
}

func (x *NestedOnlyWithOneof) SetChoiceB(v *NestedOnlyWithOneof_ChoiceB) {
	if v == nil {
		x.xxx_hidden_Selector = nil
		return
	}
	x.xxx_hidden_Selector = &nestedOnlyWithOneof_ChoiceB_{v}
}

func (x *NestedOnlyWithOneof) HasSelector() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Selector != nil
}

func (x *NestedOnlyWithOneof) HasChoiceA() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Selector.(*nestedOnlyWithOneof_ChoiceA_)
	return ok
}

func (x *NestedOnlyWithOneof) HasChoiceB() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Selector.(*nestedOnlyWithOneof_ChoiceB_)
	return ok
}

func (x *NestedOnlyWithOneof) ClearSelector() {
	x.xxx_hidden_Selector = nil
}

func (x *NestedOnlyWithOneof) ClearChoiceA() {
	if _, ok := x.xxx_hidden_Selector.(*nestedOnlyWithOneof_ChoiceA_); ok {
		x.xxx_hidden_Selector = nil
	}
}

func (x *NestedOnlyWithOneof) ClearChoiceB() {
	if _, ok := x.xxx_hidden_Selector.(*nestedOnlyWithOneof_ChoiceB_); ok {
		x.xxx_hidden_Selector = nil
	}
}

const NestedOnlyWithOneof_Selector_not_set_case case_NestedOnlyWithOneof_Selector = 0
const NestedOnlyWithOneof_ChoiceA_case case_NestedOnlyWithOneof_Selector = 1
const NestedOnlyWithOneof_ChoiceB_case case_NestedOnlyWithOneof_Selector = 2

func (x *NestedOnlyWithOneof) WhichSelector() case_NestedOnlyWithOneof_Selector {
	if x == nil {
		return NestedOnlyWithOneof_Selector_not_set_case
	}
	switch x.xxx_hidden_Selector.(type) {
	case *nestedOnlyWithOneof_ChoiceA_:
		return NestedOnlyWithOneof_ChoiceA_case
	case *nestedOnlyWithOneof_ChoiceB_:
		return NestedOnlyWithOneof_ChoiceB_case
	default:
		return NestedOnlyWithOneof_Selector_not_set_case
	}
}

type NestedOnlyWithOneof_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Selector:
	ChoiceA *NestedOnlyWithOneof_ChoiceA
	ChoiceB *NestedOnlyWithOneof_ChoiceB
	// -- end of xxx_hidden_Selector
}

func (b0 NestedOnlyWithOneof_builder) Build() *NestedOnlyWithOneof {
	m0 := &NestedOnlyWithOneof{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ChoiceA != nil {
		x.xxx_hidden_Selector = &nestedOnlyWithOneof_ChoiceA_{b.ChoiceA}
	}
	if b.ChoiceB != nil {
		x.xxx_hidden_Selector = &nestedOnlyWithOneof_ChoiceB_{b.ChoiceB}
	}
	return m0
}

type case_NestedOnlyWithOneof_Selector protoreflect.FieldNumber

func (x case_NestedOnlyWithOneof_Selector) String() string {
	md := file_models_city_v1_city_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isNestedOnlyWithOneof_Selector interface {
	isNestedOnlyWithOneof_Selector()
}

type nestedOnlyWithOneof_ChoiceA_ struct {
	ChoiceA *NestedOnlyWithOneof_ChoiceA `protobuf:"bytes,1,opt,name=choice_a,json=choiceA,proto3,oneof"`
}

type nestedOnlyWithOneof_ChoiceB_ struct {
	ChoiceB *NestedOnlyWithOneof_ChoiceB `protobuf:"bytes,2,opt,name=choice_b,json=choiceB,proto3,oneof"`
}

func (*nestedOnlyWithOneof_ChoiceA_) isNestedOnlyWithOneof_Selector() {}

func (*nestedOnlyWithOneof_ChoiceB_) isNestedOnlyWithOneof_Selector() {}

// Middle layer - has database table, contains nested_only field with oneof
type NestedOnlyMiddle struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId   string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Id         string                 `protobuf:"bytes,2,opt,name=id,proto3"`
	xxx_hidden_OneofField *NestedOnlyWithOneof   `protobuf:"bytes,3,opt,name=oneof_field,json=oneofField,proto3"`
	xxx_hidden_CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NestedOnlyMiddle) Reset() {
	*x = NestedOnlyMiddle{}
	mi := &file_models_city_v1_city_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedOnlyMiddle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedOnlyMiddle) ProtoMessage() {}

func (x *NestedOnlyMiddle) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NestedOnlyMiddle) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *NestedOnlyMiddle) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *NestedOnlyMiddle) GetOneofField() *NestedOnlyWithOneof {
	if x != nil {
		return x.xxx_hidden_OneofField
	}
	return nil
}

func (x *NestedOnlyMiddle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *NestedOnlyMiddle) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *NestedOnlyMiddle) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *NestedOnlyMiddle) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *NestedOnlyMiddle) SetOneofField(v *NestedOnlyWithOneof) {
	x.xxx_hidden_OneofField = v
}

func (x *NestedOnlyMiddle) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *NestedOnlyMiddle) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *NestedOnlyMiddle) HasOneofField() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OneofField != nil
}

func (x *NestedOnlyMiddle) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *NestedOnlyMiddle) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *NestedOnlyMiddle) ClearOneofField() {
	x.xxx_hidden_OneofField = nil
}

func (x *NestedOnlyMiddle) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *NestedOnlyMiddle) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type NestedOnlyMiddle_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId   string
	Id         string
	OneofField *NestedOnlyWithOneof
	CreatedAt  *timestamppb.Timestamp
	UpdatedAt  *timestamppb.Timestamp
}

func (b0 NestedOnlyMiddle_builder) Build() *NestedOnlyMiddle {
	m0 := &NestedOnlyMiddle{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_OneofField = b.OneofField
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

// Outer wrapper - embeds NestedOnlyMiddle to create the multi-layer nesting
type NestedOnlyWrapper struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Id        string                 `protobuf:"bytes,2,opt,name=id,proto3"`
	xxx_hidden_Middle    *NestedOnlyMiddle      `protobuf:"bytes,3,opt,name=middle,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NestedOnlyWrapper) Reset() {
	*x = NestedOnlyWrapper{}
	mi := &file_models_city_v1_city_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedOnlyWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedOnlyWrapper) ProtoMessage() {}

func (x *NestedOnlyWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NestedOnlyWrapper) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *NestedOnlyWrapper) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *NestedOnlyWrapper) GetMiddle() *NestedOnlyMiddle {
	if x != nil {
		return x.xxx_hidden_Middle
	}
	return nil
}

func (x *NestedOnlyWrapper) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *NestedOnlyWrapper) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *NestedOnlyWrapper) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *NestedOnlyWrapper) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *NestedOnlyWrapper) SetMiddle(v *NestedOnlyMiddle) {
	x.xxx_hidden_Middle = v
}

func (x *NestedOnlyWrapper) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *NestedOnlyWrapper) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *NestedOnlyWrapper) HasMiddle() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Middle != nil
}

func (x *NestedOnlyWrapper) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *NestedOnlyWrapper) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *NestedOnlyWrapper) ClearMiddle() {
	x.xxx_hidden_Middle = nil
}

func (x *NestedOnlyWrapper) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *NestedOnlyWrapper) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type NestedOnlyWrapper_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId  string
	Id        string
	Middle    *NestedOnlyMiddle
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 NestedOnlyWrapper_builder) Build() *NestedOnlyWrapper {
	m0 := &NestedOnlyWrapper{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Middle = b.Middle
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

// Test case for duplicate type generation bug.
// This structure causes both safe and unsafe query builders to have
// children with the same TypeName, which would cause duplicate type definitions.
type DuplicateTypeBugInner struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InnerValue string                 `protobuf:"bytes,1,opt,name=inner_value,json=innerValue,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DuplicateTypeBugInner) Reset() {
	*x = DuplicateTypeBugInner{}
	mi := &file_models_city_v1_city_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateTypeBugInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateTypeBugInner) ProtoMessage() {}

func (x *DuplicateTypeBugInner) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DuplicateTypeBugInner) GetInnerValue() string {
	if x != nil {
		return x.xxx_hidden_InnerValue
	}
	return ""
}

func (x *DuplicateTypeBugInner) SetInnerValue(v string) {
	x.xxx_hidden_InnerValue = v
}

type DuplicateTypeBugInner_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InnerValue string
}

func (b0 DuplicateTypeBugInner_builder) Build() *DuplicateTypeBugInner {
	m0 := &DuplicateTypeBugInner{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InnerValue = b.InnerValue
	return m0
}

type DuplicateTypeBugNested struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IndexedField   string                 `protobuf:"bytes,1,opt,name=indexed_field,json=indexedField,proto3"`
	xxx_hidden_UnindexedField string                 `protobuf:"bytes,2,opt,name=unindexed_field,json=unindexedField,proto3"`
	xxx_hidden_Inner          *DuplicateTypeBugInner `protobuf:"bytes,3,opt,name=inner,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DuplicateTypeBugNested) Reset() {
	*x = DuplicateTypeBugNested{}
	mi := &file_models_city_v1_city_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateTypeBugNested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateTypeBugNested) ProtoMessage() {}

func (x *DuplicateTypeBugNested) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DuplicateTypeBugNested) GetIndexedField() string {
	if x != nil {
		return x.xxx_hidden_IndexedField
	}
	return ""
}

func (x *DuplicateTypeBugNested) GetUnindexedField() string {
	if x != nil {
		return x.xxx_hidden_UnindexedField
	}
	return ""
}

func (x *DuplicateTypeBugNested) GetInner() *DuplicateTypeBugInner {
	if x != nil {
		return x.xxx_hidden_Inner
	}
	return nil
}

func (x *DuplicateTypeBugNested) SetIndexedField(v string) {
	x.xxx_hidden_IndexedField = v
}

func (x *DuplicateTypeBugNested) SetUnindexedField(v string) {
	x.xxx_hidden_UnindexedField = v
}

func (x *DuplicateTypeBugNested) SetInner(v *DuplicateTypeBugInner) {
	x.xxx_hidden_Inner = v
}

func (x *DuplicateTypeBugNested) HasInner() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Inner != nil
}

func (x *DuplicateTypeBugNested) ClearInner() {
	x.xxx_hidden_Inner = nil
}

type DuplicateTypeBugNested_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	IndexedField   string
	UnindexedField string
	Inner          *DuplicateTypeBugInner
}

func (b0 DuplicateTypeBugNested_builder) Build() *DuplicateTypeBugNested {
	m0 := &DuplicateTypeBugNested{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_IndexedField = b.IndexedField
	x.xxx_hidden_UnindexedField = b.UnindexedField
	x.xxx_hidden_Inner = b.Inner
	return m0
}

type DuplicateTypeBugOuter struct {
	state                protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_TenantId  string                  `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Id        string                  `protobuf:"bytes,2,opt,name=id,proto3"`
	xxx_hidden_Nested    *DuplicateTypeBugNested `protobuf:"bytes,3,opt,name=nested,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DuplicateTypeBugOuter) Reset() {
	*x = DuplicateTypeBugOuter{}
	mi := &file_models_city_v1_city_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateTypeBugOuter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateTypeBugOuter) ProtoMessage() {}

func (x *DuplicateTypeBugOuter) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DuplicateTypeBugOuter) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *DuplicateTypeBugOuter) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *DuplicateTypeBugOuter) GetNested() *DuplicateTypeBugNested {
	if x != nil {
		return x.xxx_hidden_Nested
	}
	return nil
}

func (x *DuplicateTypeBugOuter) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *DuplicateTypeBugOuter) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *DuplicateTypeBugOuter) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *DuplicateTypeBugOuter) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *DuplicateTypeBugOuter) SetNested(v *DuplicateTypeBugNested) {
	x.xxx_hidden_Nested = v
}

func (x *DuplicateTypeBugOuter) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *DuplicateTypeBugOuter) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *DuplicateTypeBugOuter) HasNested() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Nested != nil
}

func (x *DuplicateTypeBugOuter) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *DuplicateTypeBugOuter) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *DuplicateTypeBugOuter) ClearNested() {
	x.xxx_hidden_Nested = nil
}

func (x *DuplicateTypeBugOuter) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *DuplicateTypeBugOuter) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type DuplicateTypeBugOuter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId  string
	Id        string
	Nested    *DuplicateTypeBugNested
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 DuplicateTypeBugOuter_builder) Build() *DuplicateTypeBugOuter {
	m0 := &DuplicateTypeBugOuter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Nested = b.Nested
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

// Test case: embedding a message that has its own DB type.
// This should NOT cause duplicate type generation because the
// parent should NOT traverse into messages with their own DB.
type EmbeddedDBInnerConfig struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value string                 `protobuf:"bytes,1,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EmbeddedDBInnerConfig) Reset() {
	*x = EmbeddedDBInnerConfig{}
	mi := &file_models_city_v1_city_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddedDBInnerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddedDBInnerConfig) ProtoMessage() {}

func (x *EmbeddedDBInnerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EmbeddedDBInnerConfig) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *EmbeddedDBInnerConfig) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type EmbeddedDBInnerConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value string
}

func (b0 EmbeddedDBInnerConfig_builder) Build() *EmbeddedDBInnerConfig {
	m0 := &EmbeddedDBInnerConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

type EmbeddedWithOwnDB struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Id        string                 `protobuf:"bytes,2,opt,name=id,proto3"`
	xxx_hidden_Inner     *EmbeddedDBInnerConfig `protobuf:"bytes,3,opt,name=inner,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EmbeddedWithOwnDB) Reset() {
	*x = EmbeddedWithOwnDB{}
	mi := &file_models_city_v1_city_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddedWithOwnDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddedWithOwnDB) ProtoMessage() {}

func (x *EmbeddedWithOwnDB) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EmbeddedWithOwnDB) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *EmbeddedWithOwnDB) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *EmbeddedWithOwnDB) GetInner() *EmbeddedDBInnerConfig {
	if x != nil {
		return x.xxx_hidden_Inner
	}
	return nil
}

func (x *EmbeddedWithOwnDB) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *EmbeddedWithOwnDB) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *EmbeddedWithOwnDB) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *EmbeddedWithOwnDB) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *EmbeddedWithOwnDB) SetInner(v *EmbeddedDBInnerConfig) {
	x.xxx_hidden_Inner = v
}

func (x *EmbeddedWithOwnDB) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *EmbeddedWithOwnDB) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *EmbeddedWithOwnDB) HasInner() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Inner != nil
}

func (x *EmbeddedWithOwnDB) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *EmbeddedWithOwnDB) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *EmbeddedWithOwnDB) ClearInner() {
	x.xxx_hidden_Inner = nil
}

func (x *EmbeddedWithOwnDB) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *EmbeddedWithOwnDB) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type EmbeddedWithOwnDB_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId  string
	Id        string
	Inner     *EmbeddedDBInnerConfig
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 EmbeddedWithOwnDB_builder) Build() *EmbeddedWithOwnDB {
	m0 := &EmbeddedWithOwnDB{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Inner = b.Inner
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

// Parent embeds EmbeddedWithOwnDB - should NOT generate types for EmbeddedWithOwnDB's children
// because EmbeddedWithOwnDB has its own DB type and will generate those types itself.
type ParentWithEmbeddedDB struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Id        string                 `protobuf:"bytes,2,opt,name=id,proto3"`
	xxx_hidden_Embedded  *EmbeddedWithOwnDB     `protobuf:"bytes,3,opt,name=embedded,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ParentWithEmbeddedDB) Reset() {
	*x = ParentWithEmbeddedDB{}
	mi := &file_models_city_v1_city_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentWithEmbeddedDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentWithEmbeddedDB) ProtoMessage() {}

func (x *ParentWithEmbeddedDB) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ParentWithEmbeddedDB) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *ParentWithEmbeddedDB) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *ParentWithEmbeddedDB) GetEmbedded() *EmbeddedWithOwnDB {
	if x != nil {
		return x.xxx_hidden_Embedded
	}
	return nil
}

func (x *ParentWithEmbeddedDB) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *ParentWithEmbeddedDB) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *ParentWithEmbeddedDB) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *ParentWithEmbeddedDB) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *ParentWithEmbeddedDB) SetEmbedded(v *EmbeddedWithOwnDB) {
	x.xxx_hidden_Embedded = v
}

func (x *ParentWithEmbeddedDB) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *ParentWithEmbeddedDB) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *ParentWithEmbeddedDB) HasEmbedded() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Embedded != nil
}

func (x *ParentWithEmbeddedDB) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *ParentWithEmbeddedDB) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *ParentWithEmbeddedDB) ClearEmbedded() {
	x.xxx_hidden_Embedded = nil
}

func (x *ParentWithEmbeddedDB) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *ParentWithEmbeddedDB) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type ParentWithEmbeddedDB_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId  string
	Id        string
	Embedded  *EmbeddedWithOwnDB
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 ParentWithEmbeddedDB_builder) Build() *ParentWithEmbeddedDB {
	m0 := &ParentWithEmbeddedDB{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Embedded = b.Embedded
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

// Test case for duplicate method generation (Bug 1)
// When a nested message has BOTH indexed AND non-indexed fields,
// the same UnsafeQueryBuilder children are accessible from both
// the safe QueryBuilder (via UnsafeChildren) and the UnsafeQueryBuilder (via Children).
// The child's field methods should only be generated once.
type DuplicateMethodsBugLeaf struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LeafValue string                 `protobuf:"bytes,1,opt,name=leaf_value,json=leafValue,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DuplicateMethodsBugLeaf) Reset() {
	*x = DuplicateMethodsBugLeaf{}
	mi := &file_models_city_v1_city_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateMethodsBugLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateMethodsBugLeaf) ProtoMessage() {}

func (x *DuplicateMethodsBugLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DuplicateMethodsBugLeaf) GetLeafValue() string {
	if x != nil {
		return x.xxx_hidden_LeafValue
	}
	return ""
}

func (x *DuplicateMethodsBugLeaf) SetLeafValue(v string) {
	x.xxx_hidden_LeafValue = v
}

type DuplicateMethodsBugLeaf_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LeafValue string
}

func (b0 DuplicateMethodsBugLeaf_builder) Build() *DuplicateMethodsBugLeaf {
	m0 := &DuplicateMethodsBugLeaf{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LeafValue = b.LeafValue
	return m0
}

type DuplicateMethodsBugMiddle struct {
	state                     protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_IndexedField   string                   `protobuf:"bytes,1,opt,name=indexed_field,json=indexedField,proto3"`
	xxx_hidden_UnindexedField string                   `protobuf:"bytes,2,opt,name=unindexed_field,json=unindexedField,proto3"`
	xxx_hidden_Leaf           *DuplicateMethodsBugLeaf `protobuf:"bytes,3,opt,name=leaf,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DuplicateMethodsBugMiddle) Reset() {
	*x = DuplicateMethodsBugMiddle{}
	mi := &file_models_city_v1_city_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateMethodsBugMiddle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateMethodsBugMiddle) ProtoMessage() {}

func (x *DuplicateMethodsBugMiddle) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DuplicateMethodsBugMiddle) GetIndexedField() string {
	if x != nil {
		return x.xxx_hidden_IndexedField
	}
	return ""
}

func (x *DuplicateMethodsBugMiddle) GetUnindexedField() string {
	if x != nil {
		return x.xxx_hidden_UnindexedField
	}
	return ""
}

func (x *DuplicateMethodsBugMiddle) GetLeaf() *DuplicateMethodsBugLeaf {
	if x != nil {
		return x.xxx_hidden_Leaf
	}
	return nil
}

func (x *DuplicateMethodsBugMiddle) SetIndexedField(v string) {
	x.xxx_hidden_IndexedField = v
}

func (x *DuplicateMethodsBugMiddle) SetUnindexedField(v string) {
	x.xxx_hidden_UnindexedField = v
}

func (x *DuplicateMethodsBugMiddle) SetLeaf(v *DuplicateMethodsBugLeaf) {
	x.xxx_hidden_Leaf = v
}

func (x *DuplicateMethodsBugMiddle) HasLeaf() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Leaf != nil
}

func (x *DuplicateMethodsBugMiddle) ClearLeaf() {
	x.xxx_hidden_Leaf = nil
}

type DuplicateMethodsBugMiddle_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	IndexedField   string
	UnindexedField string
	Leaf           *DuplicateMethodsBugLeaf
}

func (b0 DuplicateMethodsBugMiddle_builder) Build() *DuplicateMethodsBugMiddle {
	m0 := &DuplicateMethodsBugMiddle{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_IndexedField = b.IndexedField
	x.xxx_hidden_UnindexedField = b.UnindexedField
	x.xxx_hidden_Leaf = b.Leaf
	return m0
}

type DuplicateMethodsBugRoot struct {
	state                protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_TenantId  string                     `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Id        string                     `protobuf:"bytes,2,opt,name=id,proto3"`
	xxx_hidden_Middle    *DuplicateMethodsBugMiddle `protobuf:"bytes,3,opt,name=middle,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DuplicateMethodsBugRoot) Reset() {
	*x = DuplicateMethodsBugRoot{}
	mi := &file_models_city_v1_city_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateMethodsBugRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateMethodsBugRoot) ProtoMessage() {}

func (x *DuplicateMethodsBugRoot) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DuplicateMethodsBugRoot) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *DuplicateMethodsBugRoot) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *DuplicateMethodsBugRoot) GetMiddle() *DuplicateMethodsBugMiddle {
	if x != nil {
		return x.xxx_hidden_Middle
	}
	return nil
}

func (x *DuplicateMethodsBugRoot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *DuplicateMethodsBugRoot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *DuplicateMethodsBugRoot) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *DuplicateMethodsBugRoot) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *DuplicateMethodsBugRoot) SetMiddle(v *DuplicateMethodsBugMiddle) {
	x.xxx_hidden_Middle = v
}

func (x *DuplicateMethodsBugRoot) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *DuplicateMethodsBugRoot) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *DuplicateMethodsBugRoot) HasMiddle() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Middle != nil
}

func (x *DuplicateMethodsBugRoot) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *DuplicateMethodsBugRoot) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *DuplicateMethodsBugRoot) ClearMiddle() {
	x.xxx_hidden_Middle = nil
}

func (x *DuplicateMethodsBugRoot) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *DuplicateMethodsBugRoot) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type DuplicateMethodsBugRoot_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId  string
	Id        string
	Middle    *DuplicateMethodsBugMiddle
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 DuplicateMethodsBugRoot_builder) Build() *DuplicateMethodsBugRoot {
	m0 := &DuplicateMethodsBugRoot{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Middle = b.Middle
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

// Test case for duplicate type via different paths (Bug 2)
// When a grandchild type is reachable through different intermediate paths,
// it should only be generated once.
type DuplicateTypePathsBugGrandchild struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GrandchildValue string                 `protobuf:"bytes,1,opt,name=grandchild_value,json=grandchildValue,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DuplicateTypePathsBugGrandchild) Reset() {
	*x = DuplicateTypePathsBugGrandchild{}
	mi := &file_models_city_v1_city_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateTypePathsBugGrandchild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateTypePathsBugGrandchild) ProtoMessage() {}

func (x *DuplicateTypePathsBugGrandchild) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DuplicateTypePathsBugGrandchild) GetGrandchildValue() string {
	if x != nil {
		return x.xxx_hidden_GrandchildValue
	}
	return ""
}

func (x *DuplicateTypePathsBugGrandchild) SetGrandchildValue(v string) {
	x.xxx_hidden_GrandchildValue = v
}

type DuplicateTypePathsBugGrandchild_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	GrandchildValue string
}

func (b0 DuplicateTypePathsBugGrandchild_builder) Build() *DuplicateTypePathsBugGrandchild {
	m0 := &DuplicateTypePathsBugGrandchild{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_GrandchildValue = b.GrandchildValue
	return m0
}

type DuplicateTypePathsBugChildA struct {
	state             protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Nested *DuplicateTypePathsBugGrandchild `protobuf:"bytes,1,opt,name=nested,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DuplicateTypePathsBugChildA) Reset() {
	*x = DuplicateTypePathsBugChildA{}
	mi := &file_models_city_v1_city_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateTypePathsBugChildA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateTypePathsBugChildA) ProtoMessage() {}

func (x *DuplicateTypePathsBugChildA) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DuplicateTypePathsBugChildA) GetNested() *DuplicateTypePathsBugGrandchild {
	if x != nil {
		return x.xxx_hidden_Nested
	}
	return nil
}

func (x *DuplicateTypePathsBugChildA) SetNested(v *DuplicateTypePathsBugGrandchild) {
	x.xxx_hidden_Nested = v
}

func (x *DuplicateTypePathsBugChildA) HasNested() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Nested != nil
}

func (x *DuplicateTypePathsBugChildA) ClearNested() {
	x.xxx_hidden_Nested = nil
}

type DuplicateTypePathsBugChildA_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nested *DuplicateTypePathsBugGrandchild
}

func (b0 DuplicateTypePathsBugChildA_builder) Build() *DuplicateTypePathsBugChildA {
	m0 := &DuplicateTypePathsBugChildA{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nested = b.Nested
	return m0
}

type DuplicateTypePathsBugChildB struct {
	state             protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Nested *DuplicateTypePathsBugGrandchild `protobuf:"bytes,1,opt,name=nested,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DuplicateTypePathsBugChildB) Reset() {
	*x = DuplicateTypePathsBugChildB{}
	mi := &file_models_city_v1_city_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateTypePathsBugChildB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateTypePathsBugChildB) ProtoMessage() {}

func (x *DuplicateTypePathsBugChildB) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DuplicateTypePathsBugChildB) GetNested() *DuplicateTypePathsBugGrandchild {
	if x != nil {
		return x.xxx_hidden_Nested
	}
	return nil
}

func (x *DuplicateTypePathsBugChildB) SetNested(v *DuplicateTypePathsBugGrandchild) {
	x.xxx_hidden_Nested = v
}

func (x *DuplicateTypePathsBugChildB) HasNested() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Nested != nil
}

func (x *DuplicateTypePathsBugChildB) ClearNested() {
	x.xxx_hidden_Nested = nil
}

type DuplicateTypePathsBugChildB_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nested *DuplicateTypePathsBugGrandchild
}

func (b0 DuplicateTypePathsBugChildB_builder) Build() *DuplicateTypePathsBugChildB {
	m0 := &DuplicateTypePathsBugChildB{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nested = b.Nested
	return m0
}

type DuplicateTypePathsBugRoot struct {
	state                protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_TenantId  string                               `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Id        string                               `protobuf:"bytes,2,opt,name=id,proto3"`
	xxx_hidden_Selector  isDuplicateTypePathsBugRoot_Selector `protobuf_oneof:"selector"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp               `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt *timestamppb.Timestamp               `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DuplicateTypePathsBugRoot) Reset() {
	*x = DuplicateTypePathsBugRoot{}
	mi := &file_models_city_v1_city_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateTypePathsBugRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateTypePathsBugRoot) ProtoMessage() {}

func (x *DuplicateTypePathsBugRoot) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DuplicateTypePathsBugRoot) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *DuplicateTypePathsBugRoot) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *DuplicateTypePathsBugRoot) GetChildA() *DuplicateTypePathsBugChildA {
	if x != nil {
		if x, ok := x.xxx_hidden_Selector.(*duplicateTypePathsBugRoot_ChildA); ok {
			return x.ChildA
		}
	}
	return nil
}

func (x *DuplicateTypePathsBugRoot) GetChildB() *DuplicateTypePathsBugChildB {
	if x != nil {
		if x, ok := x.xxx_hidden_Selector.(*duplicateTypePathsBugRoot_ChildB); ok {
			return x.ChildB
		}
	}
	return nil
}

func (x *DuplicateTypePathsBugRoot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *DuplicateTypePathsBugRoot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *DuplicateTypePathsBugRoot) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *DuplicateTypePathsBugRoot) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *DuplicateTypePathsBugRoot) SetChildA(v *DuplicateTypePathsBugChildA) {
	if v == nil {
		x.xxx_hidden_Selector = nil
		return
	}
	x.xxx_hidden_Selector = &duplicateTypePathsBugRoot_ChildA{v}
}

func (x *DuplicateTypePathsBugRoot) SetChildB(v *DuplicateTypePathsBugChildB) {
	if v == nil {
		x.xxx_hidden_Selector = nil
		return
	}
	x.xxx_hidden_Selector = &duplicateTypePathsBugRoot_ChildB{v}
}

func (x *DuplicateTypePathsBugRoot) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *DuplicateTypePathsBugRoot) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *DuplicateTypePathsBugRoot) HasSelector() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Selector != nil
}

func (x *DuplicateTypePathsBugRoot) HasChildA() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Selector.(*duplicateTypePathsBugRoot_ChildA)
	return ok
}

func (x *DuplicateTypePathsBugRoot) HasChildB() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Selector.(*duplicateTypePathsBugRoot_ChildB)
	return ok
}

func (x *DuplicateTypePathsBugRoot) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *DuplicateTypePathsBugRoot) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *DuplicateTypePathsBugRoot) ClearSelector() {
	x.xxx_hidden_Selector = nil
}

func (x *DuplicateTypePathsBugRoot) ClearChildA() {
	if _, ok := x.xxx_hidden_Selector.(*duplicateTypePathsBugRoot_ChildA); ok {
		x.xxx_hidden_Selector = nil
	}
}

func (x *DuplicateTypePathsBugRoot) ClearChildB() {
	if _, ok := x.xxx_hidden_Selector.(*duplicateTypePathsBugRoot_ChildB); ok {
		x.xxx_hidden_Selector = nil
	}
}

func (x *DuplicateTypePathsBugRoot) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *DuplicateTypePathsBugRoot) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

const DuplicateTypePathsBugRoot_Selector_not_set_case case_DuplicateTypePathsBugRoot_Selector = 0
const DuplicateTypePathsBugRoot_ChildA_case case_DuplicateTypePathsBugRoot_Selector = 10
const DuplicateTypePathsBugRoot_ChildB_case case_DuplicateTypePathsBugRoot_Selector = 11

func (x *DuplicateTypePathsBugRoot) WhichSelector() case_DuplicateTypePathsBugRoot_Selector {
	if x == nil {
		return DuplicateTypePathsBugRoot_Selector_not_set_case
	}
	switch x.xxx_hidden_Selector.(type) {
	case *duplicateTypePathsBugRoot_ChildA:
		return DuplicateTypePathsBugRoot_ChildA_case
	case *duplicateTypePathsBugRoot_ChildB:
		return DuplicateTypePathsBugRoot_ChildB_case
	default:
		return DuplicateTypePathsBugRoot_Selector_not_set_case
	}
}

type DuplicateTypePathsBugRoot_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId string
	Id       string
	// Fields of oneof xxx_hidden_Selector:
	ChildA *DuplicateTypePathsBugChildA
	ChildB *DuplicateTypePathsBugChildB
	// -- end of xxx_hidden_Selector
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 DuplicateTypePathsBugRoot_builder) Build() *DuplicateTypePathsBugRoot {
	m0 := &DuplicateTypePathsBugRoot{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Id = b.Id
	if b.ChildA != nil {
		x.xxx_hidden_Selector = &duplicateTypePathsBugRoot_ChildA{b.ChildA}
	}
	if b.ChildB != nil {
		x.xxx_hidden_Selector = &duplicateTypePathsBugRoot_ChildB{b.ChildB}
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type case_DuplicateTypePathsBugRoot_Selector protoreflect.FieldNumber

func (x case_DuplicateTypePathsBugRoot_Selector) String() string {
	md := file_models_city_v1_city_proto_msgTypes[18].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isDuplicateTypePathsBugRoot_Selector interface {
	isDuplicateTypePathsBugRoot_Selector()
}

type duplicateTypePathsBugRoot_ChildA struct {
	ChildA *DuplicateTypePathsBugChildA `protobuf:"bytes,10,opt,name=child_a,json=childA,proto3,oneof"`
}

type duplicateTypePathsBugRoot_ChildB struct {
	ChildB *DuplicateTypePathsBugChildB `protobuf:"bytes,11,opt,name=child_b,json=childB,proto3,oneof"`
}

func (*duplicateTypePathsBugRoot_ChildA) isDuplicateTypePathsBugRoot_Selector() {}

func (*duplicateTypePathsBugRoot_ChildB) isDuplicateTypePathsBugRoot_Selector() {}

type AttractionsConfig_Detail struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Info string                 `protobuf:"bytes,1,opt,name=info,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttractionsConfig_Detail) Reset() {
	*x = AttractionsConfig_Detail{}
	mi := &file_models_city_v1_city_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttractionsConfig_Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttractionsConfig_Detail) ProtoMessage() {}

func (x *AttractionsConfig_Detail) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AttractionsConfig_Detail) GetInfo() string {
	if x != nil {
		return x.xxx_hidden_Info
	}
	return ""
}

func (x *AttractionsConfig_Detail) SetInfo(v string) {
	x.xxx_hidden_Info = v
}

type AttractionsConfig_Detail_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Info string
}

func (b0 AttractionsConfig_Detail_builder) Build() *AttractionsConfig_Detail {
	m0 := &AttractionsConfig_Detail{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Info = b.Info
	return m0
}

type NestedOnlyWithOneof_ChoiceA struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ValueA string                 `protobuf:"bytes,1,opt,name=value_a,json=valueA,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NestedOnlyWithOneof_ChoiceA) Reset() {
	*x = NestedOnlyWithOneof_ChoiceA{}
	mi := &file_models_city_v1_city_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedOnlyWithOneof_ChoiceA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedOnlyWithOneof_ChoiceA) ProtoMessage() {}

func (x *NestedOnlyWithOneof_ChoiceA) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NestedOnlyWithOneof_ChoiceA) GetValueA() string {
	if x != nil {
		return x.xxx_hidden_ValueA
	}
	return ""
}

func (x *NestedOnlyWithOneof_ChoiceA) SetValueA(v string) {
	x.xxx_hidden_ValueA = v
}

type NestedOnlyWithOneof_ChoiceA_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ValueA string
}

func (b0 NestedOnlyWithOneof_ChoiceA_builder) Build() *NestedOnlyWithOneof_ChoiceA {
	m0 := &NestedOnlyWithOneof_ChoiceA{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ValueA = b.ValueA
	return m0
}

type NestedOnlyWithOneof_ChoiceB struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ValueB int32                  `protobuf:"varint,1,opt,name=value_b,json=valueB,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NestedOnlyWithOneof_ChoiceB) Reset() {
	*x = NestedOnlyWithOneof_ChoiceB{}
	mi := &file_models_city_v1_city_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedOnlyWithOneof_ChoiceB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedOnlyWithOneof_ChoiceB) ProtoMessage() {}

func (x *NestedOnlyWithOneof_ChoiceB) ProtoReflect() protoreflect.Message {
	mi := &file_models_city_v1_city_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NestedOnlyWithOneof_ChoiceB) GetValueB() int32 {
	if x != nil {
		return x.xxx_hidden_ValueB
	}
	return 0
}

func (x *NestedOnlyWithOneof_ChoiceB) SetValueB(v int32) {
	x.xxx_hidden_ValueB = v
}

type NestedOnlyWithOneof_ChoiceB_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ValueB int32
}

func (b0 NestedOnlyWithOneof_ChoiceB_builder) Build() *NestedOnlyWithOneof_ChoiceB {
	m0 := &NestedOnlyWithOneof_ChoiceB{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ValueB = b.ValueB
	return m0
}

var File_models_city_v1_city_proto protoreflect.FileDescriptor

const file_models_city_v1_city_proto_rawDesc = "" +
	"\n" +
	"\x19models/city/v1/city.proto\x12\x0emodels.city.v1\x1a\x16dynamo/v1/dynamo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fmodels/animals/v1/animals.proto\x1a\x17models/zoo/v1/zoo.proto\x1a\x12pgdb/v1/pgdb.proto\"\xa0\x05\n" +
	"\vAttractions\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x02id\x18\x02 \x01(\tB\x06\xd2\xf7\x02\x02\b\x01R\x02id\x12\x14\n" +
	"\x05numid\x18\x03 \x01(\x05R\x05numid\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12*\n" +
	"\x03pet\x18\n" +
	" \x01(\v2\x16.models.animals.v1.PetH\x00R\x03pet\x120\n" +
	"\bzoo_shop\x18\v \x01(\v2\x13.models.zoo.v1.ShopH\x00R\azooShop\x12+\n" +
	"\x06medium\x18\f \x01(\v2\x13.models.zoo.v1.ShopR\x06medium\x129\n" +
	"\x06config\x18\r \x01(\v2!.models.city.v1.AttractionsConfigR\x06config:\xbc\x02\x82\xf7\x02\x18\x12\x16\n" +
	"\ttenant_id\x12\x02id\x12\x05numid\xd2\xf7\x02\x9b\x02\x12#\n" +
	"\x06furrrs\x10\x03\x1a\ttenant_id\x1a\fzoo_shop.fur\x12>\n" +
	"\x12nestednestednested\x10\x03\x1a\ttenant_id\x1a\x1bzoo_shop.anything.sfixed_64\x12\x1a\n" +
	"\x05oneof\x10\x01\x1a\ttenant_id\x1a\x04what\x12,\n" +
	"\fnested_oneof\x10\x01\x1a\ttenant_id\x1a\x0fzoo_shop.medium\x12+\n" +
	"\rmedium_medium\x10\x01\x1a\ttenant_id\x1a\rmedium.medium\x12&\n" +
	"\n" +
	"petprofile\x10\x02\x1a\ttenant_id\x1a\vpet.profile\x12\x15\n" +
	"\x02id\x10\x01\x1a\ttenant_id\x1a\x02idB\x06\n" +
	"\x04what\"\x97\x01\n" +
	"\x11AttractionsConfig\x12@\n" +
	"\x06detail\x18\x01 \x01(\v2(.models.city.v1.AttractionsConfig.DetailR\x06detail\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a$\n" +
	"\x06Detail\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info:\x06\xd2\xf7\x02\x02 \x01:\x06\xd2\xf7\x02\x02 \x01\"\xc9\x01\n" +
	"\rAttractionsV2\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x129\n" +
	"\x06config\x18\x03 \x01(\v2!.models.city.v1.AttractionsConfigR\x06config\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt:\x15\x82\xf7\x02\x11\x12\x0f\n" +
	"\ttenant_id\x12\x02id\"\x95\x02\n" +
	"\x13NestedOnlyWithOneof\x12H\n" +
	"\bchoice_a\x18\x01 \x01(\v2+.models.city.v1.NestedOnlyWithOneof.ChoiceAH\x00R\achoiceA\x12H\n" +
	"\bchoice_b\x18\x02 \x01(\v2+.models.city.v1.NestedOnlyWithOneof.ChoiceBH\x00R\achoiceB\x1a*\n" +
	"\aChoiceA\x12\x17\n" +
	"\avalue_a\x18\x01 \x01(\tR\x06valueA:\x06\xd2\xf7\x02\x02 \x01\x1a*\n" +
	"\aChoiceB\x12\x17\n" +
	"\avalue_b\x18\x01 \x01(\x05R\x06valueB:\x06\xd2\xf7\x02\x02 \x01:\x06\xd2\xf7\x02\x02 \x01B\n" +
	"\n" +
	"\bselector\"\x92\x02\n" +
	"\x10NestedOnlyMiddle\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12D\n" +
	"\voneof_field\x18\x03 \x01(\v2#.models.city.v1.NestedOnlyWithOneofR\n" +
	"oneofField\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x15\x82\xf7\x02\x11\x12\x0f\n" +
	"\ttenant_id\x12\x02id\"\x87\x02\n" +
	"\x11NestedOnlyWrapper\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x128\n" +
	"\x06middle\x18\x03 \x01(\v2 .models.city.v1.NestedOnlyMiddleR\x06middle\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x15\x82\xf7\x02\x11\x12\x0f\n" +
	"\ttenant_id\x12\x02id\"@\n" +
	"\x15DuplicateTypeBugInner\x12\x1f\n" +
	"\vinner_value\x18\x01 \x01(\tR\n" +
	"innerValue:\x06\xd2\xf7\x02\x02 \x01\"\xab\x01\n" +
	"\x16DuplicateTypeBugNested\x12#\n" +
	"\rindexed_field\x18\x01 \x01(\tR\findexedField\x12'\n" +
	"\x0funindexed_field\x18\x02 \x01(\tR\x0eunindexedField\x12;\n" +
	"\x05inner\x18\x03 \x01(\v2%.models.city.v1.DuplicateTypeBugInnerR\x05inner:\x06\xd2\xf7\x02\x02 \x01\"\xca\x02\n" +
	"\x15DuplicateTypeBugOuter\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12>\n" +
	"\x06nested\x18\x03 \x01(\v2&.models.city.v1.DuplicateTypeBugNestedR\x06nested\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:N\x82\xf7\x02\x11\x12\x0f\n" +
	"\ttenant_id\x12\x02id\xd2\xf7\x025\x123\n" +
	"\x0enested_indexed\x10\x01\x1a\ttenant_id\x1a\x14nested.indexed_field\"5\n" +
	"\x15EmbeddedDBInnerConfig\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value:\x06\xd2\xf7\x02\x02 \x01\"\x8a\x02\n" +
	"\x11EmbeddedWithOwnDB\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12;\n" +
	"\x05inner\x18\x03 \x01(\v2%.models.city.v1.EmbeddedDBInnerConfigR\x05inner\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x15\x82\xf7\x02\x11\x12\x0f\n" +
	"\ttenant_id\x12\x02id\"\x8f\x02\n" +
	"\x14ParentWithEmbeddedDB\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12=\n" +
	"\bembedded\x18\x03 \x01(\v2!.models.city.v1.EmbeddedWithOwnDBR\bembedded\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x15\x82\xf7\x02\x11\x12\x0f\n" +
	"\ttenant_id\x12\x02id\"@\n" +
	"\x17DuplicateMethodsBugLeaf\x12\x1d\n" +
	"\n" +
	"leaf_value\x18\x01 \x01(\tR\tleafValue:\x06\xd2\xf7\x02\x02 \x01\"\xae\x01\n" +
	"\x19DuplicateMethodsBugMiddle\x12#\n" +
	"\rindexed_field\x18\x01 \x01(\tR\findexedField\x12'\n" +
	"\x0funindexed_field\x18\x02 \x01(\tR\x0eunindexedField\x12;\n" +
	"\x04leaf\x18\x03 \x01(\v2'.models.city.v1.DuplicateMethodsBugLeafR\x04leaf:\x06\xd2\xf7\x02\x02 \x01\"\xcf\x02\n" +
	"\x17DuplicateMethodsBugRoot\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12A\n" +
	"\x06middle\x18\x03 \x01(\v2).models.city.v1.DuplicateMethodsBugMiddleR\x06middle\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:N\x82\xf7\x02\x11\x12\x0f\n" +
	"\ttenant_id\x12\x02id\xd2\xf7\x025\x123\n" +
	"\x0emiddle_indexed\x10\x01\x1a\ttenant_id\x1a\x14middle.indexed_field\"T\n" +
	"\x1fDuplicateTypePathsBugGrandchild\x12)\n" +
	"\x10grandchild_value\x18\x01 \x01(\tR\x0fgrandchildValue:\x06\xd2\xf7\x02\x02 \x01\"n\n" +
	"\x1bDuplicateTypePathsBugChildA\x12G\n" +
	"\x06nested\x18\x01 \x01(\v2/.models.city.v1.DuplicateTypePathsBugGrandchildR\x06nested:\x06\xd2\xf7\x02\x02 \x01\"n\n" +
	"\x1bDuplicateTypePathsBugChildB\x12G\n" +
	"\x06nested\x18\x01 \x01(\v2/.models.city.v1.DuplicateTypePathsBugGrandchildR\x06nested:\x06\xd2\xf7\x02\x02 \x01\"\xf1\x02\n" +
	"\x19DuplicateTypePathsBugRoot\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12F\n" +
	"\achild_a\x18\n" +
	" \x01(\v2+.models.city.v1.DuplicateTypePathsBugChildAH\x00R\x06childA\x12F\n" +
	"\achild_b\x18\v \x01(\v2+.models.city.v1.DuplicateTypePathsBugChildBH\x00R\x06childB\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x15\x82\xf7\x02\x11\x12\x0f\n" +
	"\ttenant_id\x12\x02idB\n" +
	"\n" +
	"\bselectorB;Z9github.com/ductone/protoc-gen-pgdb/example/models/city/v1b\x06proto3"

var file_models_city_v1_city_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_models_city_v1_city_proto_goTypes = []any{
	(*Attractions)(nil),                     // 0: models.city.v1.Attractions
	(*AttractionsConfig)(nil),               // 1: models.city.v1.AttractionsConfig
	(*AttractionsV2)(nil),                   // 2: models.city.v1.AttractionsV2
	(*NestedOnlyWithOneof)(nil),             // 3: models.city.v1.NestedOnlyWithOneof
	(*NestedOnlyMiddle)(nil),                // 4: models.city.v1.NestedOnlyMiddle
	(*NestedOnlyWrapper)(nil),               // 5: models.city.v1.NestedOnlyWrapper
	(*DuplicateTypeBugInner)(nil),           // 6: models.city.v1.DuplicateTypeBugInner
	(*DuplicateTypeBugNested)(nil),          // 7: models.city.v1.DuplicateTypeBugNested
	(*DuplicateTypeBugOuter)(nil),           // 8: models.city.v1.DuplicateTypeBugOuter
	(*EmbeddedDBInnerConfig)(nil),           // 9: models.city.v1.EmbeddedDBInnerConfig
	(*EmbeddedWithOwnDB)(nil),               // 10: models.city.v1.EmbeddedWithOwnDB
	(*ParentWithEmbeddedDB)(nil),            // 11: models.city.v1.ParentWithEmbeddedDB
	(*DuplicateMethodsBugLeaf)(nil),         // 12: models.city.v1.DuplicateMethodsBugLeaf
	(*DuplicateMethodsBugMiddle)(nil),       // 13: models.city.v1.DuplicateMethodsBugMiddle
	(*DuplicateMethodsBugRoot)(nil),         // 14: models.city.v1.DuplicateMethodsBugRoot
	(*DuplicateTypePathsBugGrandchild)(nil), // 15: models.city.v1.DuplicateTypePathsBugGrandchild
	(*DuplicateTypePathsBugChildA)(nil),     // 16: models.city.v1.DuplicateTypePathsBugChildA
	(*DuplicateTypePathsBugChildB)(nil),     // 17: models.city.v1.DuplicateTypePathsBugChildB
	(*DuplicateTypePathsBugRoot)(nil),       // 18: models.city.v1.DuplicateTypePathsBugRoot
	(*AttractionsConfig_Detail)(nil),        // 19: models.city.v1.AttractionsConfig.Detail
	(*NestedOnlyWithOneof_ChoiceA)(nil),     // 20: models.city.v1.NestedOnlyWithOneof.ChoiceA
	(*NestedOnlyWithOneof_ChoiceB)(nil),     // 21: models.city.v1.NestedOnlyWithOneof.ChoiceB
	(*timestamppb.Timestamp)(nil),           // 22: google.protobuf.Timestamp
	(*v11.Pet)(nil),                         // 23: models.animals.v1.Pet
	(*v1.Shop)(nil),                         // 24: models.zoo.v1.Shop
}
var file_models_city_v1_city_proto_depIdxs = []int32{
	22, // 0: models.city.v1.Attractions.created_at:type_name -> google.protobuf.Timestamp
	23, // 1: models.city.v1.Attractions.pet:type_name -> models.animals.v1.Pet
	24, // 2: models.city.v1.Attractions.zoo_shop:type_name -> models.zoo.v1.Shop
	24, // 3: models.city.v1.Attractions.medium:type_name -> models.zoo.v1.Shop
	1,  // 4: models.city.v1.Attractions.config:type_name -> models.city.v1.AttractionsConfig
	19, // 5: models.city.v1.AttractionsConfig.detail:type_name -> models.city.v1.AttractionsConfig.Detail
	1,  // 6: models.city.v1.AttractionsV2.config:type_name -> models.city.v1.AttractionsConfig
	22, // 7: models.city.v1.AttractionsV2.created_at:type_name -> google.protobuf.Timestamp
	20, // 8: models.city.v1.NestedOnlyWithOneof.choice_a:type_name -> models.city.v1.NestedOnlyWithOneof.ChoiceA
	21, // 9: models.city.v1.NestedOnlyWithOneof.choice_b:type_name -> models.city.v1.NestedOnlyWithOneof.ChoiceB
	3,  // 10: models.city.v1.NestedOnlyMiddle.oneof_field:type_name -> models.city.v1.NestedOnlyWithOneof
	22, // 11: models.city.v1.NestedOnlyMiddle.created_at:type_name -> google.protobuf.Timestamp
	22, // 12: models.city.v1.NestedOnlyMiddle.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 13: models.city.v1.NestedOnlyWrapper.middle:type_name -> models.city.v1.NestedOnlyMiddle
	22, // 14: models.city.v1.NestedOnlyWrapper.created_at:type_name -> google.protobuf.Timestamp
	22, // 15: models.city.v1.NestedOnlyWrapper.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 16: models.city.v1.DuplicateTypeBugNested.inner:type_name -> models.city.v1.DuplicateTypeBugInner
	7,  // 17: models.city.v1.DuplicateTypeBugOuter.nested:type_name -> models.city.v1.DuplicateTypeBugNested
	22, // 18: models.city.v1.DuplicateTypeBugOuter.created_at:type_name -> google.protobuf.Timestamp
	22, // 19: models.city.v1.DuplicateTypeBugOuter.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 20: models.city.v1.EmbeddedWithOwnDB.inner:type_name -> models.city.v1.EmbeddedDBInnerConfig
	22, // 21: models.city.v1.EmbeddedWithOwnDB.created_at:type_name -> google.protobuf.Timestamp
	22, // 22: models.city.v1.EmbeddedWithOwnDB.updated_at:type_name -> google.protobuf.Timestamp
	10, // 23: models.city.v1.ParentWithEmbeddedDB.embedded:type_name -> models.city.v1.EmbeddedWithOwnDB
	22, // 24: models.city.v1.ParentWithEmbeddedDB.created_at:type_name -> google.protobuf.Timestamp
	22, // 25: models.city.v1.ParentWithEmbeddedDB.updated_at:type_name -> google.protobuf.Timestamp
	12, // 26: models.city.v1.DuplicateMethodsBugMiddle.leaf:type_name -> models.city.v1.DuplicateMethodsBugLeaf
	13, // 27: models.city.v1.DuplicateMethodsBugRoot.middle:type_name -> models.city.v1.DuplicateMethodsBugMiddle
	22, // 28: models.city.v1.DuplicateMethodsBugRoot.created_at:type_name -> google.protobuf.Timestamp
	22, // 29: models.city.v1.DuplicateMethodsBugRoot.updated_at:type_name -> google.protobuf.Timestamp
	15, // 30: models.city.v1.DuplicateTypePathsBugChildA.nested:type_name -> models.city.v1.DuplicateTypePathsBugGrandchild
	15, // 31: models.city.v1.DuplicateTypePathsBugChildB.nested:type_name -> models.city.v1.DuplicateTypePathsBugGrandchild
	16, // 32: models.city.v1.DuplicateTypePathsBugRoot.child_a:type_name -> models.city.v1.DuplicateTypePathsBugChildA
	17, // 33: models.city.v1.DuplicateTypePathsBugRoot.child_b:type_name -> models.city.v1.DuplicateTypePathsBugChildB
	22, // 34: models.city.v1.DuplicateTypePathsBugRoot.created_at:type_name -> google.protobuf.Timestamp
	22, // 35: models.city.v1.DuplicateTypePathsBugRoot.updated_at:type_name -> google.protobuf.Timestamp
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_models_city_v1_city_proto_init() }
func file_models_city_v1_city_proto_init() {
	if File_models_city_v1_city_proto != nil {
		return
	}
	file_models_city_v1_city_proto_msgTypes[0].OneofWrappers = []any{
		(*attractions_Pet)(nil),
		(*attractions_ZooShop)(nil),
	}
	file_models_city_v1_city_proto_msgTypes[3].OneofWrappers = []any{
		(*nestedOnlyWithOneof_ChoiceA_)(nil),
		(*nestedOnlyWithOneof_ChoiceB_)(nil),
	}
	file_models_city_v1_city_proto_msgTypes[18].OneofWrappers = []any{
		(*duplicateTypePathsBugRoot_ChildA)(nil),
		(*duplicateTypePathsBugRoot_ChildB)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_city_v1_city_proto_rawDesc), len(file_models_city_v1_city_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_city_v1_city_proto_goTypes,
		DependencyIndexes: file_models_city_v1_city_proto_depIdxs,
		MessageInfos:      file_models_city_v1_city_proto_msgTypes,
	}.Build()
	File_models_city_v1_city_proto = out.File
	file_models_city_v1_city_proto_goTypes = nil
	file_models_city_v1_city_proto_depIdxs = nil
}
